--File generated by preprocessor.lua
--[[This file is part of Plume
Plume🪶 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.
Plume🪶 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Plume🪶.
If not, see <https://www.gnu.org/licenses/>.
]]

return function(plume)
	plume.error = {}

	function plume.error.getNode(runtime, ip)
		local node
		for i=ip, 1, -1 do
			node = runtime.mapping[i]
			if node and node.bpos then
				break
			end
		end
		return node
	end

	function plume.error.getMacroSignature(macro)
		if macro.node then
			local paramList = plume.ast.get(macro.node, "PARAMLIST")
			if paramList then
				local signature = paramList.code:sub(paramList.bpos, paramList.epos)
				if macro.name and macro.name ~= "???" then
					return "$"..macro.name .. signature
				else
					return string.format("$<macro>%s", signature)
				end
			end
		end
	end

	local function simplifyErrorCallstack(errorCallstack)
		local windowSize = 1
		local detectedCount = 1
		while detectedCount > 0 and windowSize < #errorCallstack/2 do
			detectedCount = 0
			for i=1, #errorCallstack-windowSize do
				for j=i+windowSize, #errorCallstack, windowSize do
					local detection = true
					for k=0, windowSize do
						if not errorCallstack[i+k] or not errorCallstack[j+k] or errorCallstack[i+k].node ~= errorCallstack[j+k].node then
							detection = false
							break
						end
					end
					if not detection then
						break
					end
					detectedCount = detectedCount + i/windowSize
				end

				if detectedCount > 3 then
					local newErrorCallstack = {}
					for j=1, i-1 do
						table.insert(newErrorCallstack, errorCallstack[j])
					end
					if windowSize>1 then
						table.insert(newErrorCallstack, {repeatedBlockBegin=detectedCount})
					end

					
					for j=i, i+windowSize-1 do
						table.insert(newErrorCallstack, errorCallstack[j])
					end


					if windowSize>1 then
						table.insert(newErrorCallstack, {repeatedBlockEnd=true})
					else
						table.insert(newErrorCallstack, {repeated=detectedCount})
					end

					for j=i+(detectedCount+1)*windowSize+1, #errorCallstack do
						table.insert(newErrorCallstack, errorCallstack[j])
					end
					errorCallstack = newErrorCallstack
					break
				end
			end

			if detectedCount == 0 then
				windowSize = windowSize + 1
				detectedCount = 1
			end
		end
		return errorCallstack
	end

	local function findNodeParentMacro (node)
		if node.name == "MACRO" then
			return node
		elseif node.parent then
			return findNodeParentMacro(node.parent)
		end
	end

	function plume.error.getNodeLines(node)
		local code      = node.code
		local bpos      = node.bpos
		local epos      = node.epos
		local sourceLen = epos - bpos + 1

		local currentPos = 1
		local lines = {}
		local noLine = 1
		local sourceNoLine
		local sourceLinePosBegin
		for line in (node.code.."\n"):gmatch('[^\n]*\n') do
			if not sourceNoLine and currentPos + #line > bpos then
				sourceNoLine = noLine
				sourceLinePosBegin = bpos - currentPos + 1
				sourceLen = math.min(sourceLen, #line - sourceLinePosBegin)
			end

			lines[noLine] = line:sub(1, -2) -- remove `\n`
			currentPos = currentPos + #line
			noLine = noLine + 1
		end

		return {
			filename           = node.filename,
			lines              = lines,
			sourceNoLine       = sourceNoLine,
			sourceLinePosBegin = sourceLinePosBegin,
			sourceLen          = sourceLen
		}
	end

	function plume.error.getNodeLinesContext(node, fullContext, macroContext)
		local selectedNoLines = {}
		local selectedNoLinesCheck = {}
		local function addLine(n)
			if not selectedNoLinesCheck[n] then
				table.insert(selectedNoLines, n)
				selectedNoLinesCheck[n] = true
			end
		end

		local linesInfos = plume.error.getNodeLines(node)
		
		addLine(linesInfos.sourceNoLine)
		if fullContext then
			local prevNoLine = linesInfos.sourceNoLine-1
			while prevNoLine > 0 and linesInfos.lines[prevNoLine]:match('^%s*$') do
				prevNoLine = prevNoLine - 1
			end
			if prevNoLine > 0 then
				addLine(prevNoLine)
			end
			local nextNoLine = linesInfos.sourceNoLine+1
			while nextNoLine <= #linesInfos.lines and linesInfos.lines[nextNoLine]:match('^%s*$') do
				nextNoLine = nextNoLine + 1
			end
			if nextNoLine <= #linesInfos.lines then
				addLine(nextNoLine)
			end
		end

		if macroContext then
			local parentMacro = findNodeParentMacro (node)
			if parentMacro then
				local parentMacroInfos = plume.error.getNodeLines(parentMacro)
				addLine(parentMacroInfos.sourceNoLine)
			end
		end

		table.sort(selectedNoLines)
		local lines = {}
		local indentSize = 1/0
		local sourceLinePosBegin = linesInfos.sourceLinePosBegin
		for _, noLine in ipairs(selectedNoLines) do
			indentSize = math.min(indentSize, #linesInfos.lines[noLine]:match('^%s*'))
		end
		for _, noLine in ipairs(selectedNoLines) do
			lines[noLine] = linesInfos.lines[noLine]:gsub('\t', ' '):sub(indentSize+1, -1)
			if noLine == linesInfos.sourceNoLine then
				sourceLinePosBegin = sourceLinePosBegin - indentSize
			end
		end

		return {
			filename           = linesInfos.filename,
			sourceNoLine       = linesInfos.sourceNoLine,
			sourceLinePosBegin = sourceLinePosBegin,
			sourceLen          = linesInfos.sourceLen,
			selectedNoLines    = selectedNoLines,
			lines              = lines,
		}
	end

	function plume.error.getRuntimeErrorInfos(runtime, ip, message)
		local infos

		local node = plume.error.getNode(runtime, ip)
		local nodeParent = findNodeParentMacro(node)

		if plume.lastErrorInfos then
			infos = plume.lastErrorInfos
			infos.errorCallstack = infos.errorCallstack or {}
			table.insert(infos.errorCallstack, {node=node, parentMacro=nodeParent})
		else 
			infos = {
				header="RUNTIME ERROR:",
				message=message,
				errorCallstack={},
			}
			infos.sourceNode       = node
			infos.sourceNodeParent = nodeParent
		end
		
		if runtime.callstack then
			for i=#runtime.callstack, 1, -1 do
				local source = runtime.callstack[i]
				local node
				if source.macro.type == "macro" or source.macro.type == "luaMacro" and i>1 then
					node = plume.error.getNode(runtime, source.ip)
				end
				if node then
					local parentMacro = runtime.callstack[i-1]
					table.insert(infos.errorCallstack, {node=node, parentMacro=findNodeParentMacro(node)})
				end
			end
		end

		infos.errorCallstack = simplifyErrorCallstack(infos.errorCallstack)

		return infos
	end

	function plume.error.makeRuntimeError(runtime, ip, message)
		local errorInfos = plume.error.getRuntimeErrorInfos(runtime, ip, message)
		plume.lastErrorInfos = errorInfos
		return plume.error.formatError(errorInfos)
	end

	function plume.error.makeCompilationError(node, message)
		local errorInfos
		if plume.lastErrorInfos then
			errorInfos = plume.lastErrorInfos
			errorInfos.errorCallstack = errorInfos.errorCallstack or {}
			table.insert(errorInfos.errorCallstack, {node=node})
		else
			errorInfos = {message=message, sourceNode=node, header="COMPILATION ERROR:"}
			plume.lastErrorInfos = errorInfos
		end
		
		return plume.error.formatError(errorInfos)
	end

	function plume.error.makeSyntaxError(node, message)
		local errorInfos = {message=message, sourceNode=node, header="SYNTAX ERROR:"}
		plume.lastErrorInfos = errorInfos
		return plume.error.formatError(errorInfos)
	end

	function plume.error.makeStrictWarningError (node, message)
		local errorInfos = {message=message, sourceNode=node, header="STRICT WARNING ERROR:"}
		plume.lastErrorInfos = errorInfos
		return plume.error.formatError(errorInfos)
	end

	function plume.error.showWarnings()
		print(plume.error.formatError({}))
	end

	function plume.error.formatError(errorInfos)
		if not plume.warning.any and not errorInfos.message then
			return
		end

		local result = {}
		local maxLineNumberSize = 0

		---------------
		-- Constants --
		---------------
		local MAX_WIDTH = 80
		local BORDER_UR = "╮"
		local BORDER_UL = "╭"
		local BORDER_DR = "╯"
		local BORDER_DL = "╰"
		local BORDER_R = "┤"
		local BORDER_L = "├"

		local BORDER_H  = "─"
		local BORDER_V  = "│"

		local CODE_START  = "│"

		local HEADER_INDENT          = 1
		local SOURCE_FILENAME_INDENT = 2
		local SOURCE_CODE_INDENT     = 4

		local TRACEBACK_HEADER = "Traceback (most recent call first):"

		local MAX_WARNINGS_NODES = 3

		-----------
		-- Utils --
		-----------
		local function utf8len(s)
		    local len = 0
		    for i = 1, #s do
		        local c = s:byte(i)
		        if c < 0x80 or c >= 0xC0 then len = len + 1 end
		    end
		    return len
		end

		local function makeLine(args)
			local content         = args[1]:gsub('\t', '  ')
			local indent          = args.indent or 0
			local lineIndentDelta = args.lineIndentDelta or 0
			local crop            = args.crop
			local center          = args.center

			local leftover
			if content:match("\n") then
				local before = content:match('^[^\n]*')
				local after  = content:sub(#before+2, -1)
				makeLine{before, indent=indent, lineIndentDelta=lineIndentDelta, crop=crop}
				makeLine{after,  indent=indent+lineIndentDelta, crop=crop}
				return
			elseif utf8len(content) >= MAX_WIDTH-2 then 
				if crop then
					if crop == "start" then
						content = content:sub(1, 3)..'...'..content:sub(utf8len(content)-MAX_WIDTH+10, -1)
					else
						content = content:sub(1, MAX_WIDTH-7):gsub('%s*$', '')..'...'
					end
				else -- cut the last possible word
					local pos = 1
					for x in content:gmatch("%S+%s*") do
						if pos + utf8len(x:gsub('%s*$', '')) >= MAX_WIDTH-2 then
							break
						end
						pos = pos + #x
					end

					if pos == 1 then -- cannot find a cut point
						pos = MAX_WIDTH - 2
					end

					leftover = content:sub(pos, -1):gsub('^%s*', '')
					content = content:sub(1, pos-1):gsub('%s*$', '')
				end
			end

			local firstIndent, lastIndent

			if center then
				local space = MAX_WIDTH - utf8len(content)
				firstIndent = space/2
				lastIndent  = space/2

				if space%2==1 then
					lastIndent = lastIndent + 1
				end
			else
				firstIndent = indent
				lastIndent  = MAX_WIDTH - utf8len(content) - indent
			end

			table.insert(result,
				BORDER_V
					.. (" "):rep(firstIndent)
						.. content
					.. (" "):rep(lastIndent)
				.. BORDER_V
			)

			if leftover then
				makeLine{leftover, indent=indent+lineIndentDelta, crop=crop}
			end
		end

		local function makeSourceLine(args)
			local content = args[1]
			local noline  = args[2]
			local dindent  = args.indent or 0
			local indent = maxLineNumberSize - #tostring(noline)
			makeLine{noline .. (" "):rep(1+indent) .. CODE_START .. content, indent=SOURCE_CODE_INDENT+dindent, crop=true}
		end
		local lastfilename
		local function makeSourceSnippet(infos, indent)
			indent = indent or 0

			if infos.filename ~= lastfilename then
				makeLine{"↳ " .. infos.filename, indent=SOURCE_FILENAME_INDENT+indent, crop="start"}
				lastfilename = infos.filename
			else
				makeLine{"↳ (same file)", indent=SOURCE_FILENAME_INDENT+indent}
			end

			local lastNoLine
			for _, noLine in ipairs(infos.selectedNoLines) do
				-- if lastNoLine and lastNoLine < noLine - 1 then
				-- 	makeSourceLine{"...", "", indent=indent}
				-- end

				local line = infos.lines[noLine]
				local indicator
				if noLine == infos.sourceNoLine then
					indicator = (" "):rep(infos.sourceLinePosBegin-1) .. ("^"):rep(infos.sourceLen)
					if #indicator >= MAX_WIDTH*3/4 then
						delta     = #indicator - MAX_WIDTH*3/4
						indicator = indicator:sub(delta, -1)
						line      = "..."..line:sub(delta+3, -1)
					end
				end

				makeSourceLine{line, noLine, indent=indent}
				if indicator then
					makeSourceLine{indicator, "", indent=indent}
				end

				lastNoLine = noLine
			end
		end

		-----------------
		-- Preparation --
		-----------------
		
		local nodesInfos = {source=nil, traceback={}, warnings={count=0}}
		-- Get node infos
		if errorInfos.sourceNode then
			nodesInfos.source = plume.error.getNodeLinesContext(errorInfos.sourceNode, true, true)
		end
		for _, infos in ipairs(errorInfos.errorCallstack or {}) do
			if infos.node then
				table.insert(nodesInfos.traceback,  plume.error.getNodeLinesContext(infos.node, false, true))
			else
				table.insert(nodesInfos.traceback, infos)
			end
		end
		for i, infos in ipairs(plume.warning.cache) do
			warningInfos = {message=infos.message, help=infos.help}
			for j, node in ipairs(infos.nodes) do
				table.insert(warningInfos, plume.error.getNodeLinesContext(node, false, false))
				nodesInfos.warnings.count = nodesInfos.warnings.count + 1
			end
			table.insert(nodesInfos.warnings, warningInfos)
		end

		-- Get line number to align source code
		local allNode = {nodesInfos.source, unpack(nodesInfos.traceback)}
		for _, warningInfos in ipairs(nodesInfos.warnings) do
			for _, node in ipairs(warningInfos) do
				table.insert(allNode, node)
			end
		end

		local maxLineNumber = 1
		for _, node in ipairs(allNode) do
			for _, line in ipairs(node.selectedNoLines or {}) do
				maxLineNumber = math.max(maxLineNumber, line)
			end
		end

		maxLineNumberSize = #tostring(maxLineNumber)

		---------------
		-- Rendering --
		---------------

		-- Header
		if errorInfos.header then
			table.insert(result, BORDER_UL .. BORDER_H:rep(MAX_WIDTH) .. BORDER_UR)
			makeLine{errorInfos.header,  indent=HEADER_INDENT}
			if errorInfos.message then
				makeLine{"→ "..errorInfos.message, indent=HEADER_INDENT, lineIndentDelta=2}
			end
			table.insert(result, BORDER_L.. BORDER_H:rep(MAX_WIDTH) .. BORDER_R)
		end

		-- Source File
		if nodesInfos.source then
			makeLine{""}
			makeSourceSnippet(nodesInfos.source)
			makeLine{""}
		end

		-- Traceback
		if #nodesInfos.traceback > 0 then
			table.insert(result, BORDER_L .. BORDER_H:rep(MAX_WIDTH) .. BORDER_R)
			makeLine{TRACEBACK_HEADER, indent=HEADER_INDENT}
			table.insert(result, BORDER_L .. BORDER_H:rep(MAX_WIDTH) .. BORDER_R)
			for i, infos in ipairs(nodesInfos.traceback) do
				if infos.sourceNoLine then
					makeSourceSnippet(infos)

					if i < #nodesInfos.traceback then
						makeLine{""}
					end
				elseif infos.repeatedBlockBegin then
					makeLine{string.format("! This block is repeated %s times:", infos.repeatedBlockBegin), indent=SOURCE_FILENAME_INDENT}
					makeLine{"↳...", indent=SOURCE_FILENAME_INDENT}
				elseif infos.repeated then
					makeLine{"↳...", indent=SOURCE_FILENAME_INDENT}
					makeLine{string.format("↳(previous block is repeated %s more times)", infos.repeated), indent=SOURCE_FILENAME_INDENT}
					makeLine{"↳...", indent=SOURCE_FILENAME_INDENT}
					if i < #nodesInfos.traceback then
						makeLine{""}
					end
				elseif infos.repeatedBlockEnd then
					
					makeLine{"↳...", indent=SOURCE_FILENAME_INDENT}
					
					if i < #nodesInfos.traceback then
						makeLine{("~"):rep(MAX_WIDTH-4), indent=SOURCE_FILENAME_INDENT}
						makeLine{""}
					end
				end
			end
		end

		if nodesInfos.warnings.count > 0 then
			if errorInfos.header then
				table.insert(result, BORDER_L.. BORDER_H:rep(MAX_WIDTH) .. BORDER_R)
			else
				table.insert(result, BORDER_UL .. BORDER_H:rep(MAX_WIDTH) .. BORDER_UR)
			end

			makeLine{string.format("%s WARNING%s", nodesInfos.warnings.count, nodesInfos.warnings.count>1 and "S" or ""),  indent=HEADER_INDENT}
			makeLine{"  Add `use #warning(mode: ignore[, issues: xxx yyy])` to ignore warnings. ",  indent=HEADER_INDENT, lineIndentDelta=2}
			table.insert(result, BORDER_L.. BORDER_H:rep(MAX_WIDTH) .. BORDER_R)

			for i, warningInfos in ipairs(nodesInfos.warnings) do
				makeLine{string.format("→ WARNING %i (%i occurrences)", i, #warningInfos),  indent=HEADER_INDENT}
				makeLine{"! "..warningInfos.message,  indent=SOURCE_CODE_INDENT, lineIndentDelta=2}
				if warningInfos.help then
					makeLine{"(i) " .. warningInfos.help:gsub('^%s*', ''),  indent=SOURCE_CODE_INDENT, lineIndentDelta=4}
				end
				makeLine{""}
				for j, infos in ipairs(warningInfos) do
					makeSourceSnippet(infos, 2)

					makeLine{""}

					if j > MAX_WARNINGS_NODES then
						makeLine{string.format("↳... (%s more)", #warningInfos-j+1), indent=SOURCE_CODE_INDENT}
						makeLine{""}
						break
					end
				end

				if i<#plume.warning.cache then
					makeLine{""}
				end
			end
		end

		-- Border end
		table.insert(result, BORDER_DL.. BORDER_H:rep(MAX_WIDTH) .. BORDER_DR)

		return table.concat(result, "\n")
	end

	function plume.error.vmCrashHandler(err)
		local msg = "Unexpected internal error. Please report it at https://github.com/PlumeScript/Plume."

		msg = msg .. "\n\nLua error message:\n\t".. err
		msg = msg .. "\n"..debug.traceback("", 2)

		local ip
		-- Search for local variable "ip"
		local level = 2
		local found
        while not found do
            local info = debug.getinfo(level, "nSl")
            if not info then break end
             local i = 1
            while true do
                local name, value = debug.getlocal(level, i)
                if not name then break end
				
				if name == "vm" then
					name = "ip"
					value = value.ip
				end

                if name == "ip" then
                    found = true
                    ip = value
                    break
                end
                i = i + 1
            end
            level = level + 1
        end
		return {msg=msg, ip=ip}
	end

	function plume.safeRun(run, runtime, chunk, fileParams)
		local novmcrash, success, result, ip = xpcall(run, plume.error.vmCrashHandler, runtime, chunk, fileParams)
		
		if not novmcrash then
			result = success.msg
			ip = success.ip
			success = false
		end

		return success, result, ip
	end
end