--File generated by preprocessor.lua
--[[This file is part of Plume
Plume🪶 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.
Plume🪶 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Plume🪶.
If not, see <https://www.gnu.org/licenses/>.
]]

return function(plume)
	plume.error = {}

	function plume.error.getLineInfos(node, parentNode)
		local filename = node.filename
		local code     = node.code
		local bpos     = node.bpos
		local epos     = node.epos
		local len      = 0
		local content  = code:sub(bpos, epos)
		
		plume.ast.browse(node, function(child)
			if child.bpos and child.bpos < bpos then
				bpos = child.bpos
			end
		end)

		local capturedLine, capturedPrevLine, capturedNextLine, capturedBPos
		local capturedNoPrevline, capturedNoNextline
		local capturedNoline = 0
		local currentPos = 0

		for line in (code.."\n"):gmatch('[^\n]*\n') do
			capturedNoline = capturedNoline + 1
			
			if currentPos + #line >= bpos then
				capturedLine = line
				currentPos = currentPos+1
				break
			end
			currentPos = currentPos + #line
			if not line:match('^%s*$') then
				capturedPrevLine = line
				capturedNoPrevline = capturedNoline
			end
		end

		if not capturedLine then
			return
		end
		
		if capturedLine:match('\n$') then
			capturedLine = capturedLine:gsub('\n$', '')
		end
		if capturedPrevLine and capturedPrevLine:match('\n$') then
			capturedPrevLine = capturedPrevLine:gsub('\n$', '')
		end

		if currentPos < #code then
			capturedNoNextline = capturedNoline+1
			capturedNextLine = ""
			local delta = 0
			while true do
				capturedNextLine = code:sub(currentPos+#capturedLine+delta, -1):match('^\n[^\n]*')
				if not capturedNextLine then
					capturedNoNextline = nil
					break
				end
				if capturedNextLine:match('^%s*$') then
					delta = delta + #capturedNextLine
					capturedNoNextline = capturedNoNextline + 1
				else
					capturedNextLine = capturedNextLine:gsub('^\n*', '')
					break
				end
			end
		end

		local parentLine, parentNoLine
		if parentNode then
			local parentInfos = plume.error.getLineInfos(parentNode)
			if parentInfos.noline < capturedNoPrevline or capturedNoline then
				parentLine = parentInfos.line
				parentNoLine = parentInfos.noline
			end
		end

		capturedPrevLine = capturedPrevLine and capturedPrevLine:gsub('\t', ' ')
		capturedLine = capturedLine:gsub('\t', ' ')
		capturedNextLine = capturedNextLine and capturedNextLine:gsub('\t', ' ')
		
		len  = math.min(epos - bpos + 1, #capturedLine - (bpos - currentPos))
		bpos = bpos - currentPos

		local indent = #capturedLine:match('^%s*')
		if capturedPrevLine then
			indent = math.min(indent, #capturedPrevLine:match('^%s*'))
		end
		if capturedNextLine then
			indent = math.min(indent, #capturedNextLine:match('^%s*'))
		end

		if capturedPrevLine then
			capturedPrevLine = capturedPrevLine:sub(indent+1, -1)
		end
		capturedLine = capturedLine:sub(indent+1, -1)
		if capturedNextLine then
			capturedNextLine = capturedNextLine:sub(indent+1, -1)
		end

		bpos = bpos - indent + 1
		return {
			parentLine = parentLine,
			parentNoLine = parentNoLine,
			prevLine = capturedPrevLine,
			line     = capturedLine,
			nextLine = capturedNextLine,
			content  = content,
			noprevline   = capturedNoPrevline,
			nonextline   = capturedNoNextline,
			noline   = capturedNoline,
			bpos     = bpos,
			len      = len,
			filename = node.filename,
		}
	end

	function plume.error.formatLine(lineInfos, macro, syntax)
		local intro = string.format(
			"%sFile '%s', line %i",
			syntax and "" or "  ",
			lineInfos.filename,
			lineInfos.noline
		)

		if macro then
			intro = intro .. ", in macro " .. macro
		end

		local msg = intro

		msg = msg .. ": " ..lineInfos.line .. "\n"
		msg = msg .. (" "):rep(#intro + lineInfos.bpos+1) .. ("^"):rep(lineInfos.len)

		return msg
	end

	function plume.error.getNode(runtime, ip)
		local node
		for i=ip, 1, -1 do
			node = runtime.mapping[i]
			if node and node.bpos then
				break
			end
		end
		return node
	end

	function plume.error.makeMessage(message, node)
		if node and node.bpos then
			local lineInfos = plume.error.getLineInfos(node)
			message = message .. "\n"..plume.error.formatLine(lineInfos, nil, true)
		else
			message = "Unexpected error"
		end

		return message
	end

	local function simplifyErrorCallstack(errorCallstack)
		local windowSize = 1
		local detectedCount = 1
		while detectedCount > 0 and windowSize < #errorCallstack/2 do
			detectedCount = 0
			for i=1, #errorCallstack-windowSize do
				for j=i+windowSize, #errorCallstack, windowSize do
					local detection = true
					for k=0, windowSize do
						if not errorCallstack[i+k] or not errorCallstack[j+k] or errorCallstack[i+k].node ~= errorCallstack[j+k].node then
							detection = false
							break
						end
					end
					if not detection then
						break
					end
					detectedCount = detectedCount + i/windowSize
				end

				if detectedCount > 3 then
					local newErrorCallstack = {}
					for j=1, i-1 do
						table.insert(newErrorCallstack, errorCallstack[j])
					end
					if windowSize>1 then
						table.insert(newErrorCallstack, {repeatedBlockBegin=detectedCount})
					end

					
					for j=i, i+windowSize-1 do
						table.insert(newErrorCallstack, errorCallstack[j])
					end


					if windowSize>1 then
						table.insert(newErrorCallstack, {repeatedBlockEnd=true})
					else
						table.insert(newErrorCallstack, {repeated=detectedCount})
					end

					for j=i+(detectedCount+1)*windowSize+1, #errorCallstack do
						table.insert(newErrorCallstack, errorCallstack[j])
					end
					errorCallstack = newErrorCallstack
					break
				end
			end

			if detectedCount == 0 then
				windowSize = windowSize + 1
				detectedCount = 1
			end
		end
		return errorCallstack
	end

	local function findNodeParentMacro (node)
		if node.name == "MACRO" then
			return node
		elseif node.parent then
			return findNodeParentMacro(node.parent)
		end
	end

	function plume.error.getRuntimeErrorInfos(runtime, ip, message)
		local infos

		local node = plume.error.getNode(runtime, ip)
		local nodeParent = findNodeParentMacro(node)

		if plume.lastErrorInfos then
			infos = plume.lastErrorInfos
			infos.errorCallstack = infos.errorCallstack or {}
			table.insert(infos.errorCallstack, {node=node, parentMacro=nodeParent})
		else 
			infos = {
				header="RUNTIME ERROR:",
				message=message,
				errorCallstack={},
			}
			infos.sourceNode       = node
			infos.sourceNodeParent = nodeParent
		end
		
		if runtime.callstack then
			for i=#runtime.callstack, 1, -1 do
				local source = runtime.callstack[i]
				local node
				if source.macro.type == "macro" or source.macro.type == "luaFunction" and i>1 then
					node = plume.error.getNode(runtime, source.ip)
				end
				if node then
					local parentMacro = runtime.callstack[i-1]
					table.insert(infos.errorCallstack, {node=node, parentMacro=findNodeParentMacro(node)})
				end
			end
		end

		infos.errorCallstack = simplifyErrorCallstack(infos.errorCallstack)

		return infos
	end

	function plume.error.makeRuntimeError(runtime, ip, message)
		local errorInfos = plume.error.getRuntimeErrorInfos(runtime, ip, message)
		plume.lastErrorInfos = errorInfos
		return plume.error.formatError(errorInfos)
	end

	function plume.error.makeCompilationError(node, message)
		local errorInfos
		if plume.lastErrorInfos then
			errorInfos = plume.lastErrorInfos
			errorInfos.errorCallstack = errorInfos.errorCallstack or {}
			table.insert(errorInfos.errorCallstack, {node=node})
		else
			errorInfos = {message=message, sourceNode=node, header="COMPILATION ERROR:"}
			plume.lastErrorInfos = errorInfos
		end
		
		return plume.error.formatError(errorInfos)
	end

	function plume.error.makeSyntaxError(node, message)
		local errorInfos = {message=message, sourceNode=node, header="SYNTAX ERROR:"}
		plume.lastErrorInfos = errorInfos
		return plume.error.formatError(errorInfos)
	end

	function plume.error.makeStrictWarningError (node, message)
		local errorInfos = {message=message, sourceNode=node, header="STRICT WARNING ERROR:"}
		plume.lastErrorInfos = errorInfos
		return plume.error.formatError(errorInfos)
	end

	function plume.error.showWarnings()
		print(plume.error.formatError({}))
	end

	function plume.error.formatError(errorInfos)
		if not plume.warning.any and not errorInfos.message then
			return
		end

		local result = {}
		local width = 0
		local maxLineNumberSize = 0

		---------------
		-- Constants --
		---------------
		local MAX_WIDTH = 80
		local BORDER_UR = "╮"
		local BORDER_UL = "╭"
		local BORDER_DR = "╯"
		local BORDER_DL = "╰"
		local BORDER_R = "┤"
		local BORDER_L = "├"

		local BORDER_H  = "─"
		local BORDER_V  = "│"

		local CODE_START  = "│"

		local HEADER_INDENT          = 1
		local SOURCE_FILENAME_INDENT = 2
		local SOURCE_CODE_INDENT     = 4

		local TRACEBACK_HEADER = "Traceback (most recent call first):"

		local MAX_WARNINGS_NODES = 3

		-----------
		-- Utils --
		-----------
		local function utf8len(s)
		    local len = 0
		    for i = 1, #s do
		        local c = s:byte(i)
		        if c < 0x80 or c >= 0xC0 then len = len + 1 end
		    end
		    return len
		end

		local function makeLine(args)
			local content         = args[1]:gsub('\t', '  ')
			local indent          = args.indent or 0
			local lineIndentDelta = args.lineIndentDelta or 0
			local crop            = args.crop
			local center          = args.center

			local leftover
			if content:match("\n") then
				local before = content:match('^[^\n]*')
				local after  = content:sub(#before+2, -1)
				makeLine{before, indent=indent, lineIndentDelta=lineIndentDelta, crop=crop}
				makeLine{after,  indent=indent+lineIndentDelta, crop=crop}
				return
			elseif utf8len(content) >= width-2 then 
				if crop then
					if crop == "start" then
						content = content:sub(1, 3)..'...'..content:sub(utf8len(content)-width+10, -1)
					else
						content = content:sub(1, width-7):gsub('%s*$', '')..'...'
					end
				else -- cut the last possible word
					local pos = 1
					for x in content:gmatch("%S+%s*") do
						if pos + utf8len(x:gsub('%s*$', '')) >= width-2 then
							break
						end
						pos = pos + #x
					end

					if pos == 1 then -- cannot find a cut point
						pos = width - 2
					end

					leftover = content:sub(pos, -1):gsub('^%s*', '')
					content = content:sub(1, pos-1):gsub('%s*$', '')
				end
			end

			local firstIndent, lastIndent

			if center then
				local space = width - utf8len(content)
				firstIndent = space/2
				lastIndent  = space/2

				if space%2==1 then
					lastIndent = lastIndent + 1
				end
			else
				firstIndent = indent
				lastIndent  = width - utf8len(content) - indent
			end

			table.insert(result,
				BORDER_V
					.. (" "):rep(firstIndent)
						.. content
					.. (" "):rep(lastIndent)
				.. BORDER_V
			)

			if leftover then
				makeLine{leftover, indent=indent+lineIndentDelta, crop=crop}
			end
		end

		local function makeSourceLine(args)
			local content = args[1]
			local noline  = args[2]
			local dindent  = args.indent or 0
			local indent = maxLineNumberSize - #tostring(noline)
			makeLine{noline .. (" "):rep(1+indent) .. CODE_START .. content, indent=SOURCE_CODE_INDENT+dindent, crop=true}
		end
		local lastfilename
		local function makeSourceSnippet(args)
			local node    = args[1]
			local infos   = args[2]
			local indent  = args.indent or 0
			local context = args.context

			if infos.filename ~= lastfilename then
				makeLine{infos.filename, indent=SOURCE_FILENAME_INDENT+indent, crop="start"}
				lastfilename = infos.filename
			else
				makeLine{"↳ (same file)", indent=SOURCE_FILENAME_INDENT+indent, crop=true}
			end

			if infos.parentLine then
				if infos.parentNoLine < (args.context and infos.noprevline or infos.noline) and infos.parentNoLine < infos.noline then
					makeSourceLine{infos.parentLine, infos.parentNoLine, indent=indent}
		
					if infos.parentNoLine < (args.context and infos.noprevline or infos.noline) - 1 and infos.parentNoLine < infos.noline then
						local sindent = infos.line:match('^%s*')
						makeSourceLine{sindent.."...", "", indent=indent}
					end
				end
			end

			if args.context and infos.prevLine then
				makeSourceLine{infos.prevLine, infos.noprevline, indent=indent}
			end
			local line = infos.line:gsub('\t', ' ')
			local indicator

			local widthlimit = math.floor(3*width/4)
			if infos.bpos+infos.len>widthlimit then
				local delta = infos.bpos + infos.len + 4 - widthlimit
				line = "..."..line:sub(delta, -1)
				indicator = (" "):rep(maxLineNumberSize+1) .. CODE_START .. (" "):rep(infos.bpos+3-delta) .. ("^"):rep(infos.len)
			else
				indicator = (" "):rep(maxLineNumberSize+1) .. CODE_START .. (" "):rep(infos.bpos-1) .. ("^"):rep(infos.len)
			end

			makeSourceLine{line, infos.noline, indent=indent}
			makeLine{indicator, indent=SOURCE_CODE_INDENT+indent, crop=true}
			if args.context and infos.nextLine then
				makeSourceLine{infos.nextLine, infos.nonextline, indent=indent}
			end
		end

		-----------------
		-- Preparation --
		-----------------
		
		-- Get node infos
		local sourceNodeInfos
		if errorInfos.sourceNode then
			sourceNodeInfos = plume.error.getLineInfos(errorInfos.sourceNode, errorInfos.sourceNodeParent)
			sourceNodeInfos.filename = "↳ " .. sourceNodeInfos.filename
		end
		for _, infos in ipairs(errorInfos.errorCallstack or {}) do
			if infos.node then
				infos.infos = plume.error.getLineInfos(infos.node, infos.parentMacro)
				infos.infos.filename = "↳ " .. infos.infos.filename
			end
		end
		for i, infos in ipairs(plume.warning.cache) do
			for j, node in ipairs(infos.nodes) do
				node.infos = plume.error.getLineInfos(node)
				node.infos.filename = "↳ " .. node.infos.filename
			end
		end

		-- Get width
		-- width = math.max(width,  utf8len(errorInfos.header)  + 2 * HEADER_INDENT)
		-- width = math.max(width,  utf8len(errorInfos.message) + 2 * HEADER_INDENT)

		-- width = math.max(width,  utf8len(sourceNodeInfos.filename)   + 2 * SOURCE_FILENAME_INDENT)

		-- width = math.max(width,  utf8len(TRACEBACK_HEADER) + 2 * HEADER_INDENT)
		-- for _, infos in ipairs(errorInfos.errorCallstack or {}) do
		-- 	width = math.max(width,  utf8len(infos.infos.filename) + 2 * SOURCE_FILENAME_INDENT)
		-- end

		-- width = math.min(width, MAX_WIDTH)
		width = MAX_WIDTH

		-- Get line number to align source code
		if sourceNodeInfos then
			if sourceNodeInfos.nonextline then
				maxLineNumberSize = math.max(maxLineNumberSize,  sourceNodeInfos.nonextline)
			else
				maxLineNumberSize = math.max(maxLineNumberSize,  sourceNodeInfos.noline)
			end
		end
		for _, infos in ipairs(errorInfos.errorCallstack or {}) do
			if infos.node then
				if infos.infos.nonextline then
					maxLineNumberSize = math.max(maxLineNumberSize,  infos.infos.nonextline)
				else
					maxLineNumberSize = math.max(maxLineNumberSize,  infos.infos.noline)
				end
			end
		end
		for i, infos in ipairs(plume.warning.cache) do
			for j, node in ipairs(infos.nodes) do
				if node.infos.nonextline then
					maxLineNumberSize = math.max(maxLineNumberSize,  node.infos.nonextline)
				else
					maxLineNumberSize = math.max(maxLineNumberSize,  node.infos.noline)
				end
			end
		end

		maxLineNumberSize = #tostring(maxLineNumberSize)

		---------------
		-- Rendering --
		---------------

		-- Header
		if errorInfos.header then
			table.insert(result, BORDER_UL .. BORDER_H:rep(width) .. BORDER_UR)
			makeLine{errorInfos.header,  indent=HEADER_INDENT}
			if errorInfos.message then
				makeLine{"→ "..errorInfos.message, indent=HEADER_INDENT, lineIndentDelta=2}
			end
			table.insert(result, BORDER_L.. BORDER_H:rep(width) .. BORDER_R)
		end

		-- Source File
		if errorInfos.sourceNode and sourceNodeInfos then
			makeLine{""}
			makeSourceSnippet{errorInfos.sourceNode, sourceNodeInfos, context=true}
			makeLine{""}
		end

		-- Traceback
		if errorInfos.errorCallstack and #errorInfos.errorCallstack > 0 then
			table.insert(result, BORDER_L .. BORDER_H:rep(width) .. BORDER_R)
			makeLine{TRACEBACK_HEADER, indent=HEADER_INDENT}
			table.insert(result, BORDER_L .. BORDER_H:rep(width) .. BORDER_R)
			for i, infos in ipairs(errorInfos.errorCallstack or {}) do
				if infos.node then
					makeSourceSnippet{infos.node, infos.infos}

					if i < #errorInfos.errorCallstack then
						makeLine{""}
					end
				elseif infos.repeatedBlockBegin then
					makeLine{string.format("! This block is repeated %s times:", infos.repeatedBlockBegin), indent=SOURCE_FILENAME_INDENT}
					makeLine{"↳...", indent=SOURCE_FILENAME_INDENT}
				elseif infos.repeated then
					makeLine{"↳...", indent=SOURCE_FILENAME_INDENT}
					makeLine{string.format("↳(previous block is repeated %s more times)", infos.repeated), indent=SOURCE_FILENAME_INDENT}
					makeLine{"↳...", indent=SOURCE_FILENAME_INDENT}
					if i < #errorInfos.errorCallstack then
						makeLine{""}
					end
				elseif infos.repeatedBlockEnd then
					
					makeLine{"↳...", indent=SOURCE_FILENAME_INDENT}
					
					if i < #errorInfos.errorCallstack then
						makeLine{("~"):rep(width-4), indent=SOURCE_FILENAME_INDENT}
						makeLine{""}
					end
				end
			end
		end

		if plume.warning.any then
			local wcount = 0
			for i, infos in ipairs(plume.warning.cache) do
				wcount = wcount + #infos.nodes
			end

			if errorInfos.header then
				table.insert(result, BORDER_L.. BORDER_H:rep(width) .. BORDER_R)
			else
				table.insert(result, BORDER_UL .. BORDER_H:rep(width) .. BORDER_UR)
			end

			makeLine{string.format("%s WARNINGS", wcount),  indent=HEADER_INDENT}
			makeLine{"  Add `use #warning(mode: ignore[, issues: xxx yyy])` to ignore warnings. ",  indent=HEADER_INDENT, lineIndentDelta=2}
			table.insert(result, BORDER_L.. BORDER_H:rep(width) .. BORDER_R)

			for i, infos in ipairs(plume.warning.cache) do
				makeLine{string.format("→ WARNING %i (%i occurrences)", i, #infos.nodes),  indent=HEADER_INDENT}
				makeLine{"! "..infos.message,  indent=SOURCE_CODE_INDENT, lineIndentDelta=2}
				if infos.help then
					makeLine{"(i) " .. infos.help:gsub('^%s*', ''),  indent=SOURCE_CODE_INDENT, lineIndentDelta=4}
				end
				makeLine{""}

				for j, node in ipairs(infos.nodes) do
					makeSourceSnippet{node, node.infos, indent=2}

					makeLine{""}

					if j > MAX_WARNINGS_NODES then
						makeLine{string.format("↳... (%s more)", #infos.nodes-j+1),  indent=SOURCE_CODE_INDENT}
						makeLine{""}
						break
					end
				end

				

				if i<#plume.warning.cache then
					makeLine{""}
				end
			end
		end

		-- Border end
		table.insert(result, BORDER_DL.. BORDER_H:rep(width) .. BORDER_DR)

		return table.concat(result, "\n")
	end

	function plume.error.vmCrashHandler(err)
		local msg = "Unexpected internal error. Please report it at https://github.com/PlumeScript/Plume."

		msg = msg .. "\n\nLua error message:\n\t".. err
		msg = msg .. "\n"..debug.traceback("", 2)

		local ip
		-- Search for local variable "ip"
		local level = 2
		local found
        while not found do
            local info = debug.getinfo(level, "nSl")
            if not info then break end
             local i = 1
            while true do
                local name, value = debug.getlocal(level, i)
                if not name then break end
				
				if name == "vm" then
					name = "ip"
					value = value.ip
				end

                if name == "ip" then
                    found = true
                    ip = value
                    break
                end
                i = i + 1
            end
            level = level + 1
        end
		return {msg=msg, ip=ip}
	end

	function plume.safeRun(run, runtime, chunk, fileParams)
		local novmcrash, success, result, ip = xpcall(run, plume.error.vmCrashHandler, runtime, chunk, fileParams)
		
		if not novmcrash then
			result = success.msg
			ip = success.ip
			success = false
		end

		return success, result, ip
	end
end