--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]


-- Generated by build-tools/make-std.lua

return function(plume)
	plume.std = {}
    plume.stdUtils = {}

	
	
	plume.stdio = {}
	function plume.stdio.write(path, content, append)
		local mode = append and "a" or "w"
		local file = io.open(path, mode)
			if not file then
				return false, "Cannot write file '" .. path .. "'."
			end
			file:write(content)
		file:close()
		return true
	end
	
	function plume.stdio.read(path)
		local file = io.open(path)
			if not file then
				return false, "Cannot read file '" .. path .. "'."
			end
			local content = file:read("*a")
		file:close()
		return true, content
	end
	    
	plume.std.print = plume.obj.luaMacro("print", function (args)
	    local result = {}
	    for _, x in ipairs(args.table) do
	        table.insert(result, plume.repr(x, nil, args.table.pretty))
	    end
	    print(table.unpack(result))
	    return true
	end)
	
	plume.std.help = plume.obj.luaMacro("help", function (args)
	    local __name      = "print"
	    local __signature = "`$print(macro macro)`"
	    local __s, __e, self, macro
	    __s, __e, macro = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if __s and macro then __s, __e, macro = plume.stdCheckType(macro, "macro", "1", __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    local name = macro.debugMacroName or macro.name
	    local doc = macro.doc or ""
	    print("macro " .. name .. "\n    " .. doc:gsub('\n', '\n    ') or "")
	    return true
	end)
	
	-- io
	plume.std.write = plume.obj.luaMacro("write", function (args)
	    local __name      = "write"
	    local __signature = "`$write(string filename, string content, ?append)`"
	    local __s, __e, self, filename, content
	    __s, __e, filename, content = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
	    local append
	    if __s then __s, __e, self, append = plume.stdUnpackNamed(args, {"self", "append"}, __name, __signature) end
	    append = append or false
	    if __s and filename then __s, __e, filename = plume.stdCheckType(filename, "string", "1", __name, __signature) end
	    if __s and content then __s, __e, content = plume.stdCheckType(content, "string", "2", __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    return plume.stdio.write(filename, content, append)
	end)
	
	plume.std.read = plume.obj.luaMacro("read", function (args)
	    local __name      = "read"
	    local __signature = "`$read(string filename)`"
	    local __s, __e, self, filename
	    __s, __e, filename = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if __s and filename then __s, __e, filename = plume.stdCheckType(filename, "string", "1", __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    return plume.stdio.read(filename)
	end)
	
	plume.std.rawset = plume.obj.luaMacro("rawset", function (args)
	    local __name      = "rawset"
	    local __signature = "`$rawset(table obj, string key, any value)`"
	    local __s, __e, self, obj, key, value
	    __s, __e, obj, key, value = plume.stdUnpackPositional(args, 3, 3,  __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if __s and obj then __s, __e, obj = plume.stdCheckType(obj, "table", "1", __name, __signature) end
	    if __s and key then __s, __e, key = plume.stdCheckType(key, "string", "2", __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	
	    if not obj.table[key] then
	        table.insert(obj.keys, key)
	    end
	    obj.table[key] = value
	    return true
	end)
	
	plume.std.repr = plume.obj.luaMacro("repr", function (args)
	    local __name      = "repr"
	    local __signature = "`$repr(any obj, ?pretty)`"
	    local __s, __e, self, obj
	    __s, __e, obj = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	    local pretty
	    if __s then __s, __e, self, pretty = plume.stdUnpackNamed(args, {"self", "pretty"}, __name, __signature) end
	    pretty = pretty or false
	    if not __s then return false, __e end
	    ------------
	    return true, plume.repr(obj, nil, pretty)
	end)
	
	plume.std.min = plume.obj.luaMacro("min", function (args)
	    local __name      = "min"
	    local __signature = "`$min(number ...numbers)`"
	    local __s, __e, self = plume.stdUnpackPositional(args, 0, math.huge, __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    return true, math.min(unpack(args.table))
	end)
	plume.std.max = plume.obj.luaMacro("max", function (args)
	    local __name      = "max"
	    local __signature = "`$max(number ...numbers)`"
	    local __s, __e, self = plume.stdUnpackPositional(args, 0, math.huge, __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    return true, math.max(unpack(args.table))
	end)
	
	plume.std.List = plume.obj.table(0, 0)
	plume.std.List.meta = plume.obj.quickTable{
	    call = plume.obj.luaMacro ("call", function (args)
	        local __name      = "List"
	        local __signature = "`$List(table t)`"
	        local __s, __e, self, t
	        __s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        local result = plume.obj.table(0, 0)
	        for k, v in ipairs(t.table) do
	            table.insert(result.keys, k)
	            table.insert(result.table, v)
	        end
	        return true, result
	    end),
	    validate = plume.obj.luaMacro ("validate", function (args)
	        local __name      = "validate"
	        local __signature = "`$List(table t)`"
	        local __s, __e, self, t
	        __s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        for _, k in ipairs(t.keys) do
	            if not tonumber(k) then
	                return false, string.format("Received extra named argument '%s', but extra arguments must be positional.", k)
	            end
	        end
	
	        return true, args
	    end)
	}
	
	plume.std.Map = plume.obj.table(0, 0)
	plume.std.Map.meta = plume.obj.quickTable{
	    call = plume.obj.luaMacro ("call", function (args)
	        local __name      = "Map"
	        local __signature = "`$Map(table t)`"
	        local __s, __e, self, t
	        __s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        local result = plume.obj.table(0, 0)
	        for _, k in ipairs(t.keys) do
	            if not tonumber(k) then
	                table.insert(result.keys, k)
	                result.table[k] = t.table[k]
	            end
	        end
	        return true, result
	    end),
	    validate = plume.obj.luaMacro ("validate", function (args)
	        local __name      = "validate"
	        local __signature = "`$Map(table t)`"
	        local __s, __e, self, t
	        __s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        for _, k in ipairs(t.keys) do
	            if tonumber(k) then
	                return false, "Received an extra positional argument, but extra arguments must be named."
	            end
	        end
	
	        return true, args
	    end)
	}
	
	local function importLuaMacro(name, f)
	    return plume.obj.luaMacro(name, function(args, runtime, _, ip)
	        plume.warning.runtimeWarning(string.format("Deprecated macro '%s', as all `lua.*` macros.\nWill be removed in edition 'Owl'.", name), "Use std instead.", runtime, ip, {614, 615, 649})
	        local success, result = pcall(f, unpack(args.table))
	        return success, result
	    end)
	end
	
	local function importLuaTable(name, t)
	    local result = plume.obj.table(0, 0)
	
	    for k, v in pairs(t) do
	        table.insert(result.keys, k)
	        if type(v) == "table" then
	            v = importLuaTable(k, v)
	        elseif type(v) == "function" then
	            v = importLuaMacro(k, v)
	        end
	        result.table[k] = v
	    end
	
	    return result
	end
	
	plume.std.lua = plume.obj.table(0, 0)
	
	for name in ("assert error"):gmatch("%S+") do
	    plume.std.lua.table[name] = importLuaMacro(name, _G[name])
	end
	
	for name in ("string math os io"):gmatch("%S+") do
	    plume.std.lua.table[name] = importLuaTable(name, _G[name])
	end
	
	plume.std.lua.table.require =  plume.obj.luaMacro("require", function(args, runtime, fileID)
	    local firstFilename = runtime.files[1].name
	    local lastFilename  = runtime.files[fileID].name
	
	    local filename, searchPaths = plume.getFilenameFromPath(args.table[1], true, runtime, firstFilename, lastFilename)
	    if filename then
	        return true, dofile(filename)(plume) 
	    else
	        msg = "Error: cannot open '" .. args.table[1] .. "'.\nPaths tried:\n\t" .. table.concat(searchPaths, '\n\t')
	        return false, msg
	    end
	end)
	
	plume.std.attempt = plume.obj.table(0, 0)
	
	plume.std.Math = plume.obj.quickTable{
	    sin = plume.obj.luaMacro("sin", function (args)
	        local __name      = "sin"
	        local __signature = "`$sin(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.sin(x)
	    end),
	    cos = plume.obj.luaMacro("cos", function (args)
	        local __name      = "cos"
	        local __signature = "`$cos(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.cos(x)
	    end),
	    tan = plume.obj.luaMacro("tan", function (args)
	        local __name      = "tan"
	        local __signature = "`$tan(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.tan(x)
	    end),
	    asin =  plume.obj.luaMacro("asin", function (args)
	        local __name      = "asin"
	        local __signature = "`$asin(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.asin(x)
	    end),
	    acos =  plume.obj.luaMacro("acos", function (args)
	        local __name      = "acos"
	        local __signature = "`$acos(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.acos(x)
	    end),
	    atan =  plume.obj.luaMacro("atan", function (args)
	        local __name      = "atan"
	        local __signature = "`$atan(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.atan(x)
	    end),
	    atan2 =  plume.obj.luaMacro("atan2", function (args)
	        local __name      = "atan2"
	        local __signature = "`$atan2(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.atan2(x, y)
	    end),
	    sinh =  plume.obj.luaMacro("sinh", function (args)
	        local __name      = "sinh"
	        local __signature = "`$sinh(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.sinh(x)
	    end),
	    cosh =  plume.obj.luaMacro("cosh", function (args)
	        local __name      = "cosh"
	        local __signature = "`$cosh(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.cosh(x)
	    end),
	    tanh =  plume.obj.luaMacro("tanh", function (args)
	        local __name      = "tanh"
	        local __signature = "`$tanh(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.tanh(x)
	    end),
	    log =  plume.obj.luaMacro("log", function (args)
	        local __name      = "log"
	        local __signature = "`$log(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.log(x)
	    end),
	    log10 =  plume.obj.luaMacro("log10", function (args)
	        local __name      = "log10"
	        local __signature = "`$log10(number x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.log10(x)
	    end),
	    pi   = math.pi,
	    e    = math.exp(1),
	    huge = math.huge
	}
	
	plume.formatNumber = function(x, format, locale, thousandsSeparator, decimalSeparator, thousandthsSeparator)
		if thousandsSeparator == plume.obj.empty then
			thousandsSeparator = nil
		end
		if thousandthsSeparator == plume.obj.empty then
			thousandthsSeparator = nil
		end
		if not format or format == plume.obj.empty then
			format = "%s"
		end
	
		local result = string.format(format, x)
		if locale then
			local integerPart, decimalPart
			if result:gmatch('%.') then
				integerPart = result:match('^[^%.]+')
				decimalPart = result:match('%.([^%.]+)')
			else
				integerPart = result
			end
	
			if locale == "en" or locale == "us" then
				thousandsSeparator = ","
				decimalSeparator  = "."
			elseif locale == "fr" then
				thousandsSeparator    = " "
				decimalSeparator     = ","
				thousandthsSeparator = " "
			elseif locale == "custom" then
				thousandsSeparator    = thousandsSeparator or nil
				decimalSeparator     = decimalSeparator or "."
				thousandthsSeparator = thousandthsSeparator or nil
			elseif locale then
				return false, "Unknown localization format '" .. locale .. "'."
			end
	
			if thousandsSeparator then
				thousandsSeparator = thousandsSeparator:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
				integerPart = integerPart:gsub("(.)(...)$", "%1"..thousandsSeparator.."%2")
				for i=1, #integerPart do
					integerPart = integerPart:gsub("([0-9])([0-9][0-9][0-9])"..thousandsSeparator, "%1"..thousandsSeparator.."%2"..thousandsSeparator)
				end
			end
			result = integerPart
	
			if decimalPart then
				if thousandthsSeparator then
					thousandthsSeparator = thousandthsSeparator:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
					decimalPart = decimalPart:gsub("^([0-9][0-9][0-9])([0-9])", "%1"..thousandthsSeparator.."%2")
					for i=1, #integerPart do
						decimalPart = decimalPart:gsub(thousandthsSeparator.."([0-9][0-9][0-9])([0-9])", "%1"..thousandthsSeparator.."%2"..thousandthsSeparator)
					end
				end
	
				result = result .. decimalSeparator .. decimalPart
			end
		end
	
		return true, result
	end
	
	plume.std.Number = plume.obj.quickTable{
		-- Manipulations
		floor = plume.obj.luaMacro("floor", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "floor"
			local __signature = "`$floor(number x, number digit:0)`"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local digit
			if __s then __s, __e, self, digit = plume.stdUnpackNamed(args, {"self", "digit"}, __name, __signature) end
			digit = digit or 0
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
			if __s and digit then __s, __e, digit = plume.stdCheckType(digit, "number", "digit", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.floor(x*10^digit)*10^-digit
		end),
		ceil = plume.obj.luaMacro("ceil", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "ceil"
			local __signature = "`$ceil(number x, number digit:0)`"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local digit
			if __s then __s, __e, self, digit = plume.stdUnpackNamed(args, {"self", "digit"}, __name, __signature) end
			digit = digit or 0
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
			if __s and digit then __s, __e, digit = plume.stdCheckType(digit, "number", "digit", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.ceil(x*10^digit)*10^-digit
		end),
		round = plume.obj.luaMacro("round", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "round"
			local __signature = "`$round(number x, number digit:0)`"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local digit
			if __s then __s, __e, self, digit = plume.stdUnpackNamed(args, {"self", "digit"}, __name, __signature) end
			digit = digit or 0
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
			if __s and digit then __s, __e, digit = plume.stdCheckType(digit, "number", "digit", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.floor(x*10^digit + 0.5)*10^-digit
		end),
		abs = plume.obj.luaMacro("abs", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "abs"
			local __signature = "`$abs(number x)`"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.abs(x)
		end),
		clamp = plume.obj.luaMacro("clamp", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "clamp"
			local __signature = "`$clamp(number x, number min, number max)`"
			local __s, __e, self, x, min, max
			__s, __e, x, min, max = plume.stdUnpackPositional(args, 3, 3,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
			if __s and min then __s, __e, min = plume.stdCheckType(min, "number", "2", __name, __signature) end
			if __s and max then __s, __e, max = plume.stdCheckType(max, "number", "3", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.min(max, math.max(min, x))
		end),
		format = plume.obj.luaMacro("format", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "format"
			local __signature = "`$format(number x, string format, string locale:, string thousandsSeparator:, string decimalSeparator:, string thousandthsSeparator:)`"
			local __s, __e, self, x, format
			__s, __e, x, format = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local locale, thousandsSeparator, decimalSeparator, thousandthsSeparator
			if __s then __s, __e, self, locale, thousandsSeparator, decimalSeparator, thousandthsSeparator = plume.stdUnpackNamed(args, {"self", "locale", "thousandsSeparator", "decimalSeparator", "thousandthsSeparator"}, __name, __signature) end
			locale = locale or nil
			thousandsSeparator = thousandsSeparator or nil
			decimalSeparator = decimalSeparator or nil
			thousandthsSeparator = thousandthsSeparator or nil
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
			if __s and format then __s, __e, format = plume.stdCheckType(format, "string", "2", __name, __signature) end
			if not __s then return false, __e end
			------------
			return plume.formatNumber(
				x, format, locale, thousandsSeparator, decimalSeparator, thousandthsSeparator
			)
		end),
		localize = plume.obj.luaMacro("format", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "format"
			local __signature = "`$format(number x, string locale)`"
			local __s, __e, self, x, locale
			__s, __e, x, locale = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
			if __s and locale then __s, __e, locale = plume.stdCheckType(locale, "string", "2", __name, __signature) end
			if not __s then return false, __e end
			------------
			return plume.formatNumber(x, "%s", locale)
		end),
	
		-- Test
		sign = plume.obj.luaMacro("sign", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "sign"
			local __signature = "`$sign(number x)`"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			if x>0 then
				return true, 1
			elseif x<0 then
				return true, -1
			else
				return true, 0
			end
		end)
	}
	
	plume.std.Number.meta = plume.obj.quickTable {
		call = plume.obj.luaMacro("Number", function(args)
			local x = args.table[1]
			if x == plume.obj.empty then
				return false, "Cannot convert empty into number"
			elseif type(x) == "number" then
				return true, x
			elseif tonumber(x) then
				return true, tonumber(x)
			else
			   return false, string.format("Cannot convert %s into number", type(x))
			end
		end)
	}
	
	plume.std.os = plume.obj.quickTable {
	    getEnv = plume.obj.luaMacro("getEnv", function (args)
	        local __name      = "getEnv"
	        local __signature = "`$getEnv(string name)`"
	        local __s, __e, self, name
	        __s, __e, name = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and name then __s, __e, name = plume.stdCheckType(name, "string", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, os.getenv(name)
	    end),
	
	    -- Very basic implementation
	    execute = plume.obj.luaMacro("execute", function (args)
	        local __name      = "execute"
	        local __signature = "`$execute(string command)`"
	        local __s, __e, self, command
	        __s, __e, command = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and command then __s, __e, command = plume.stdCheckType(command, "string", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	    	local success, result = pcall(function()
	    	    local h = io.popen(command)
	    		if not h then
	    			return nil
	    		end
	    		local r = h:read("*a")
	    		h:close()
	    		return r
	    	end)
	        return success, result
	    end)
	}
	
	local lfs = require"lfs"
	
	local function mkdirs(path, isFile)
		local fullPath = ""
		path = path:gsub('\\', '/')
		for frag in path:gmatch('[^/]+') do
			if fullPath ~= "" or path:sub(1, 1) == "/" then
				fullPath = fullPath .. "/"
			end
			fullPath = fullPath .. frag
			if isFile and path == fullPath then
				break
			end
	
			local attr = lfs.attributes(fullPath)
			if not attr then
				local success, result = lfs.mkdir(fullPath)
				if not success then
					return false, result
				end
			end
		end
		return true
	end
	
	local function makePath(path)
		local obj = plume.obj.quickTable{
			path = path or lfs.currentdir (),
			isFile = plume.obj.luaMacro ("isFile", function (args)
				local __name      = "isFile"
				local __signature = "`$isFile()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
	
				if not attr then
					return true, false
				end
	
				return true, attr.mode == "file"
			end),
			isDirectory = plume.obj.luaMacro ("isDirectory", function (args)
				local __name      = "isDirectory"
				local __signature = "`$isDirectory()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
	
				if not attr then
					return true, false
				end
	
				return true, attr.mode == "directory"
			end),
			exists = plume.obj.luaMacro ("exists", function (args)
				local __name      = "exists"
				local __signature = "`$exists()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
				return true, attr ~= nil
			end),
			make = plume.obj.luaMacro ("make", function (args)
				local __name      = "make"
				local __signature = "`$make()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
	
				if attr then
					return false, string.format("'%s' already exists, cannot create it.", path)
				end
	
				return mkdirs(path)
			end),
			remove = plume.obj.luaMacro ("remove", function (args)
				local __name      = "remove"
				local __signature = "`$remove()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
	
				if not attr then
					return false, string.format("'%s' don't exists, cannot remove it.", path)
				end
	
				if attr.mode == "file" then
					return os.remove(path)
				else
					return lfs.rmdir(path)
				end
	
			end),
			move = plume.obj.luaMacro ("move", function (args)
				local __name      = "move"
				local __signature = "`$move(string newpath)`"
				local __s, __e, self, newpath
				__s, __e, newpath = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if __s and newpath then __s, __e, newpath = plume.stdCheckType(newpath, "string", "1", __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
	
				if not attr then
					return false, string.format("'%s' don't exists, cannot move it.", path)
				end
	
				args.table.self.table.path = newpath
				return os.rename(path, newpath)
			end),
			copy = plume.obj.luaMacro ("copy", function (args)
				local __name      = "copy"
				local __signature = "`$copy()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local newpath = args.table[1]
	
				local src = io.open(path)
				if not src then
					return false, string.format("Cannot read '%s'", src)
				end
				local dest = io.open(newpath, "w")
				if not dest then
					return false, string.format("Cannot write '%s'", dest)
				end
	
				dest:write(src:read("*a"))
				src:close()
				dest:close()
	
				return makePath(newpath)
			end),
	
			getParent = plume.obj.luaMacro ("getParent", function (args)
				local __name      = "getParent"
				local __signature = "`$getParent()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
	
				if path:match('[/\\]') then
					return makePath(path:gsub('[/\\][^/\\]*$', ''))
				else
					return false, "Cannot return parent of root"
				end
			end),
			getName = plume.obj.luaMacro ("getName", function (args)
				local __name      = "getName"
				local __signature = "`$getName()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				return true, path:match('[^/\\]*$')
			end),
			read = plume.obj.luaMacro ("read", function (args)
				local __name      = "read"
				local __signature = "`$read()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				return plume.stdio.read(path)
			end),
			write = plume.obj.luaMacro ("write", function (args)
				local __name      = "write"
				local __signature = "`$write(?append, string ...items)`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, math.huge, __name, __signature)
				local append
				if __s then __s, __e, self, append = plume.stdUnpackNamed(args, {"self", "append"}, __name, __signature) end
				append = append or false
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local success, result = mkdirs(path, true)
				if not success then
					return false, result
				end
	
				return plume.stdio.write(path, table.concat(args.table), append)
			end),
			touch = plume.obj.luaMacro ("touch", function (args)
				local __name      = "touch"
				local __signature = "`$touch()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local success, result = mkdirs(path, true)
				if not success then
					return false, result
				end
	
				local file = io.open(path, "w")
				if not file then
					return false, string.format("Cannot touch '%s'", path)
				end
				file:close()
				return true
			end),
			getChildren = plume.obj.luaMacro ("getChildren", function (args)
				local __name      = "getChildren"
				local __signature = "`$getChildren()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local result = plume.obj.table(0, 0)
	
				for child in lfs.dir(path) do
					if child ~= "." and child ~= ".." then
						local _, childPath = makePath(path.."/"..child)
						table.insert(result.table, childPath)
						table.insert(result.keys, #result.table)
					end
				end
				return true, result
			end),
			walk = plume.obj.luaMacro ("walk", function (args)
				local __name      = "walk"
				local __signature = "`$walk()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				local result = plume.obj.table(0, 0)
	
				local toExplore = {path}
				local pos = 1
				while pos <= #toExplore do
					local path = toExplore[pos]
					pos = pos + 1
	
					for child in lfs.dir(path) do
						if child ~= "." and child ~= ".." then
							local childPath = path.."/"..child
							local _, childPathObj = makePath(childPath)
							table.insert(result.table, childPathObj)
							table.insert(result.keys, #result.table)
	
							table.insert(toExplore, childPath)
						end
					end
				end
				return true, result
			end)
		}
	
		obj.subtype = "Path"
	
		local function div(x1, x2)
			local path1, path2
	
			if type(x1) == "string" then
				path1 = x1
			else
				path1 = x1.table.path
			end
	
			if type(x2) == "string" then
				path2 = x2
			else
				path2 = x2.table.path
			end
	
			return makePath(path1 .. "/" .. path2)
		end
	
		obj.meta = plume.obj.quickTable{
			tostring = plume.obj.luaMacro ("tostring", function (args)
				local __name      = "tostring"
				local __signature = "`$tostring()`"
				local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if not __s then return false, __e end
				------------
				local path = args.table.self.table.path
				return true, path
			end),
	
			div = plume.obj.luaMacro ("div", function (args)
				local __name      = "div"
				local __signature = "`$div(Path|string x, Path|string y)`"
				local __s, __e, self, x, y
				__s, __e, x, y = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if __s and x then
					__s, __e, x = plume.stdCheckType(x, "Path", "1", __name, __signature)
					if not __s then
						__s, __e, x = plume.stdCheckType(x, "string", "1", __name, __signature)
					end
				end
				if __s and y then
					__s, __e, y = plume.stdCheckType(y, "Path", "2", __name, __signature)
					if not __s then
						__s, __e, y = plume.stdCheckType(y, "string", "2", __name, __signature)
					end
				end
				if not __s then return false, __e end
				------------
				return div(x, y)
			end)
		}
		
		return true, obj
	end
	
	table.insert(plume.std.os.keys, "Path")
	plume.std.os.table.Path = plume.obj.luaMacro("Path", function (args)
	    local __name      = "Path"
	    local __signature = "`$Path([string path])`"
	    local __s, __e, self, path
	    __s, __e, path = plume.stdUnpackPositional(args, 0, 1,  __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if __s and path then __s, __e, path = plume.stdCheckType(path, "string", "1", __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    return makePath(path)
	end)
	
	-- plume.std.plume isn't loaded like other std table,
	-- but copied at runtime creation
	
	plume.std.plume = plume.obj.quickTable {
		doc = plume.obj.luaMacro("doc", function (args)
			local __name      = "doc"
			local __signature = "`$doc(macro m)`"
			local __s, __e, self, m
			__s, __e, m = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and m then __s, __e, m = plume.stdCheckType(m, "macro", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, "macro " .. (m.debugMacroName or m.name) .. "\n    " .. m.doc:gsub('\n', '\n    ') or ""
		end)
	}
	
	plume.std.Random = plume.obj.luaMacro("Random", function (args)
		local __name      = "Random"
		local __signature = "`$Random([number seed])`"
		local __s, __e, self, seed
		__s, __e, seed = plume.stdUnpackPositional(args, 0, 1,  __name, __signature)
		if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
		if __s and seed then __s, __e, seed = plume.stdCheckType(seed, "number", "1", __name, __signature) end
		if not __s then return false, __e end
		------------
	    function _deriveSeed(seed, index)
			seed = ((seed + index * 1234567) * 1103515245 + 12345) % 2147483647
			if seed==0 then
				return 1
			else
				return seed
			end
		end
		local state = _deriveSeed(args.table[1] or os.time(), 1)
	
	    function _random()
	    	state = ((state * 48271) % 2147483647)
			return (state / 2147483647)
	    end
	    function _random_range(a, b)
			return math.floor(_random() * (b-a+1) + a)
	    end
	
	    local function shuffle(t)
			for k=1, #t.table do
				local i = _random_range(1, #t.table)
				local j = _random_range(1, #t.table)
	
				t.table[i], t.table[j] = t.table[j], t.table[i]
			end
		end
	   	
	    local random = plume.obj.quickTable{
		    seed = plume.obj.luaMacro ("seed", function (args)
		    	local __name      = "seed"
		    	local __signature = "`$seed([number seed])`"
		    	local __s, __e, self, seed
		    	__s, __e, seed = plume.stdUnpackPositional(args, 0, 1,  __name, __signature)
		    	if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
		    	if __s and seed then __s, __e, seed = plume.stdCheckType(seed, "number", "1", __name, __signature) end
		    	if not __s then return false, __e end
		    	------------
		    	state = _deriveSeed(seed or os.time(), 1)
		    	return true
			end),
		    choice = plume.obj.luaMacro ("choice", function (args)
		    	local __name      = "choice"
		    	local __signature = "`$choice(table t)`"
		    	local __s, __e, self, t
		    	__s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
		    	if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
		    	if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
		    	if not __s then return false, __e end
		    	------------
		    	return true, t.table[_random_range(1, #t.table)]
			end),
			pchoice = plume.obj.luaMacro ("pchoice", function (args)
				local __name      = "pchoice"
				local __signature = "`$pchoice(table t)`"
				local __s, __e, self, t
				__s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
				if not __s then return false, __e end
				------------
				local tw = 0
				for _, k in ipairs(t.keys) do
					local v = t.table[k]
					if type(v) == "number" then
						tw = tw + v
					end
				end
				local r = _random() * tw
				tw = 0
				for _, k in ipairs(t.keys) do
					local v = t.table[k]
					if type(v) == "number" then
						tw = tw + v
						if tw>=r then
							return true, k
						end
					end
				end
			end),
			shuffle = plume.obj.luaMacro ("shuffle", function (args)
				local __name      = "shuffle"
				local __signature = "`$shuffle(table t)`"
				local __s, __e, self, t
				__s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
				if not __s then return false, __e end
				------------
				shuffle(t)
		    	return true
			end),
			sample = plume.obj.luaMacro ("sample", function (args)
				local __name      = "sample"
				local __signature = "`$sample(table t, number count)`"
				local __s, __e, self, t, count
				__s, __e, t, count = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
				if __s and count then __s, __e, count = plume.stdCheckType(count, "number", "2", __name, __signature) end
				if not __s then return false, __e end
				------------
				if count > #t.table then
					return false, string.format("Cannot give a '%i'-size sample of a table with '%i' element%s.",
						count, #t.table, "s" and #t.table>1 or "")
				end
				t = plume.stdUtils.copy(t)
				shuffle(t)
	
				for i=#t.table, count+1, -1 do
					for j, key in ipairs(t.keys) do
						if key==i then
		    				t.keys[j] = nil
		    				break
		    			end
					end
					t.table[i] = nil
				end
		    	return true, t
			end)
		}
		random.meta = plume.obj.quickTable{
			call = plume.obj.luaMacro ("call", function(args)
				if #args.table == 0 then
		        	return true, _random()
		        elseif #args.table == 1 then
		        	return true, _random_range(0, args.table[1])
		        elseif #args.table == 2 then
		        	return true, _random_range(args.table[1], args.table[2])
		        end
			end)
		}
	    
	    return true, random
	end)
	
	local function replaceUpdate(context)
		local s       = context.string
		local pos     = context.pos
		local pattern = context.pattern
		local acc     = context.acc
	
		local bpos, epos = s:sub(pos, -1):find(pattern)
	
		if bpos then
			context.PLUME_CALLBACK = context.macro
			table.insert(acc, s:sub(pos, pos+bpos-2))
			context.PLUME_CALLBACK_ARGS = {s:sub(pos+bpos-1, pos+epos-1)}
			context.pos = context.pos+epos
		else
			context.PLUME_CALLBACK = nil
			table.insert(acc, s:sub(pos, -1))
			context.pos = #s+1
			context.RETURN_VALUE = table.concat(acc)
		end
		return true
	end
	
	local function replaceNext(context, value)
		local t = type(value) == "table" and value.type or type(value)
		if t ~= "string" and t ~= "number" and t ~= "empty" then
			return false, string.format("Macro sub for `String.replace` must return a 'string' or a 'number', not a '%s'.", t)
		end
	
		if (type(value) ~= "table" or value.type ~= "empty") then
			table.insert(context.acc, value)
		end
		return true
	end
	
	plume.std.String = plume.obj.quickTable {
	
		-- Manipulation
		upper = plume.obj.luaMacro("upper", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "upper"
			local __signature = "`$upper(string s)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, string.upper(s)
		end),
		lower = plume.obj.luaMacro("lower", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "lower"
			local __signature = "`$lower(string s)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, string.lower(s)
		end),
	
		replace = plume.obj.luaMacro("replace", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "replace"
			local __signature = "`$replace(string s, string pattern, string|macro sub, ?rich)`"
			local __s, __e, self, s, pattern, sub
			__s, __e, s, pattern, sub = plume.stdUnpackPositional(args, 3, 3,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "2", __name, __signature) end
			if __s and sub then
				__s, __e, sub = plume.stdCheckType(sub, "string", "3", __name, __signature)
				if not __s then
					__s, __e, sub = plume.stdCheckType(sub, "macro", "3", __name, __signature)
				end
			end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
				if type(sub) == "string" then
					sub = sub:gsub("%%", "%%%%")
				end
			end
	
			if type(sub) ~= "string" then
				if sub.positionalParamCount ~= 1 then
					return false, string.format("Macro sub for `String.replace` must take exactly '1' argument, not '%i'.", sub.positionalParamCount)
				end
	
				local context = {
					type         = "hostContext",
					string       = s,
					pattern      = pattern,
					pos          = 1,
					macro        = sub,
					acc          = {},
					HOST_UPDATE  = replaceUpdate,
					HOST_NEXT    = replaceNext
				}
				return true, context, true
			end
	
			return true, (s:gsub(pattern, sub))
		end),
	
		-- Tests
		isNumber = plume.obj.luaMacro("isNumber", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "isNumber"
			local __signature = "`$isNumber(string s)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			if tonumber(s) then
				return true, true
			else
				return true, false
			end
		end),
	
		-- Normalization
		trim = plume.obj.luaMacro("trim", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "trim"
			local __signature = "`$trim(string s)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, (s:gsub('^%s*', ''):gsub('%s*$', ''))
		end),
		rtrim = plume.obj.luaMacro("rtrim", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "rtrim"
			local __signature = "`$rtrim(string s)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, (s:gsub('^%s*', ''))
		end),
		ltrim = plume.obj.luaMacro("ltrim", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "ltrim"
			local __signature = "`$ltrim(string s)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, (s:gsub('%s*$', ''))
		end),
		collapse = plume.obj.luaMacro("collapse", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "collapse"
			local __signature = "`$collapse(string s)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, (s:gsub('%s+', ' '))
		end),
		dedent = plume.obj.luaMacro("dedent", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "dedent"
			local __signature = "`$dedent(string s)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			local firstIndent = s:match('^%s+')
			return true, (s:gsub('^'..firstIndent, ''):gsub('\n'..firstIndent, '\n'))
		end),
		indent = plume.obj.luaMacro("indent", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "indent"
			local __signature = "`$indent(string s, string sep:\\t)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local sep
			if __s then __s, __e, self, sep = plume.stdUnpackNamed(args, {"self", "sep"}, __name, __signature) end
			sep = sep or "\t"
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and sep then __s, __e, sep = plume.stdCheckType(sep, "string", "sep", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, sep..s:gsub('\n', '\n'..sep)
		end),
	
		-- search
		find = plume.obj.luaMacro("find", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "find"
			local __signature = "`$find(string s, string pattern, ?rich)`"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "2", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			return true, (s:match(pattern) or plume.empty)
		end),
		contains = plume.obj.luaMacro("contains", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "contains"
			local __signature = "`$contains(string s, string pattern, ?rich)`"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "2", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			if s:match(pattern) then
				return true, true
			else
				return true, false
			end
		end),
		startsWidth = plume.obj.luaMacro("startsWidth", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "startsWidth"
			local __signature = "`$startsWidth(string s, string pattern, ?rich)`"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "2", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			if s:match("^"..pattern) then
				return true, true
			else
				return true, false
			end
		end),
		endsWidth = plume.obj.luaMacro("endsWidth", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "endsWidth"
			local __signature = "`$endsWidth(string s, string pattern, ?rich)`"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "2", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			if s:match(pattern.."$") then
				return true, true
			else
				return true, false
			end
		end),
		count = plume.obj.luaMacro("count", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "count"
			local __signature = "`$count(string s, string pattern, ?rich)`"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "2", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			local count = 0
			for x in s:gmatch(pattern) do
				count = count + 1
			end
	
			return true, count
		end),
	
		-- table making
		split = plume.obj.luaMacro("split", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "split"
			local __signature = "`$split(string s, string sep:\\s, ?rich)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local sep, rich
			if __s then __s, __e, self, sep, rich = plume.stdUnpackNamed(args, {"self", "sep", "rich"}, __name, __signature) end
			sep = sep or " "
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and sep then __s, __e, sep = plume.stdCheckType(sep, "string", "sep", __name, __signature) end
			if not __s then return false, __e end
			------------
			local t = plume.obj.table(0, 0)
	
			if not rich then
				sep = sep:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			local pos = 1
			for sub, _sep in s:gmatch('(.-)('..sep..")") do
				table.insert(t.table, sub)
				table.insert(t.keys, #t.table)
				pos = pos + #sub + #_sep
			end
	
			if pos <= #s then
				table.insert(t.table, s:sub(pos, -1))
				table.insert(t.keys, #t.table)
			end
	
			return true, t
		end),
		lines = plume.obj.luaMacro("lines", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "lines"
			local __signature = "`$lines(string s)`"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			local t = plume.obj.table(0, 0)
	
			local pos = 1
			for sub in s:gmatch('(.-)\n') do
				table.insert(t.table, sub)
				table.insert(t.keys, #t.table)
				pos = pos + #sub + 1
			end
	
			if pos <= #s then
				table.insert(t.table, s:sub(pos, -1))
				table.insert(t.keys, #t.table)
			end
	
			return true, t
		end),
		findAll = plume.obj.luaMacro("findAll", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "findAll"
			local __signature = "`$findAll(string s, string pattern, ?rich)`"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "2", __name, __signature) end
			if not __s then return false, __e end
			------------
	
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			local t = plume.obj.table(0, 0)
	
			for sub in s:gmatch(pattern) do
				table.insert(t.table, sub)
				table.insert(t.keys, #t.table)
			end
	
			return true, t
		end),
		partition = plume.obj.luaMacro("partition", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "partition"
			local __signature = "`$partition(string s, string pattern, ?rich)`"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "2", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			local t = plume.obj.table(3, 0)
			t.keys = {1, 2, 3}
			t.table[1], t.table[2], t.table[3] = s:match("(.-)("..pattern..")(.+)")
	
			return true, t
		end),
	
		rep = plume.obj.luaMacro("rep", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "rep"
			local __signature = "`$rep(string s, number count, string sep:$empty)`"
			local __s, __e, self, s, count
			__s, __e, s, count = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local sep
			if __s then __s, __e, self, sep = plume.stdUnpackNamed(args, {"self", "sep"}, __name, __signature) end
			sep = sep or ""
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and count then __s, __e, count = plume.stdCheckType(count, "number", "2", __name, __signature) end
			if __s and sep then __s, __e, sep = plume.stdCheckType(sep, "string", "sep", __name, __signature) end
			if not __s then return false, __e end
			------------
			count = tonumber(count)
			local result = {}
			for i=1, count do
				table.insert(result, s)
				if i<count then
					table.insert(result, sep)
				end
			end
	
			return true, table.concat(result)
		end),
	
		sub = plume.obj.luaMacro("sub", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "sub"
			local __signature = "`$sub(string s, number startpos, number endpos)`"
			local __s, __e, self, s, startpos, endpos
			__s, __e, s, startpos, endpos = plume.stdUnpackPositional(args, 3, 3,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "1", __name, __signature) end
			if __s and startpos then __s, __e, startpos = plume.stdCheckType(startpos, "number", "2", __name, __signature) end
			if __s and endpos then __s, __e, endpos = plume.stdCheckType(endpos, "number", "3", __name, __signature) end
			if not __s then return false, __e end
			------------
			if epos == 1 then
				epos = #s
			end
	
			return true, s:sub(startpos, endpos)
		end)
	}
	
	local function sortUpdate(context)
	    if context.j == context.i then
	        table.insert(context.result, context.source.table[context.i])
	        context.i = context.i + 1
	        context.j = 1
	    end
	
	    if context.i <= #context.source.table then
	        context.PLUME_CALLBACK = context.compare
	        context.PLUME_CALLBACK_ARGS = {
	            context.result[context.j],
	            context.source.table[context.i]
	        }
	    else
	        context.PLUME_CALLBACK = nil
	        context.source.table = context.result
	    end
	
	    return true
	end
	
	local function sortNext(context, value)
	    if value then
	        context.j = context.j + 1
	    else
	        table.insert(context.result, context.j, context.source.table[context.i])
	        context.i = context.i + 1
	        context.j = 1
	    end
	    return true
	end
	
	function plume.stdUtils.copy(t, deep, nt)
	    local nt = nt or plume.obj.table(#t.table, #t.keys)
	
	    for _, key in ipairs(t.keys) do
	        local rawvalue = t.table[key]
	        local value
	        if deep and type(rawvalue) == "table" and rawvalue.type == "table" then
	            if deep[rawvalue] then
	                value = deep[rawvalue]
	            else
	                deep[rawvalue] = plume.obj.table(0, 0)
	                value = plume.stdUtils.copy(rawvalue, deep, deep[rawvalue])
	            end
	        else
	            value = rawvalue
	        end
	
	        table.insert(nt.keys, key)
	        nt.table[key] = value
	    end
	
	    return nt
	end
	
	plume.std.Table = plume.obj.quickTable{
	    remove = plume.obj.luaMacro("remove", function (args)
	        local __name      = "remove"
	        local __signature = "`$remove(table t, [string|number index])`"
	        local __s, __e, self, t, index
	        __s, __e, t, index = plume.stdUnpackPositional(args, 1, 2,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if __s and index then
	        	__s, __e, index = plume.stdCheckType(index, "string", "2", __name, __signature)
	        	if not __s then
	        		__s, __e, index = plume.stdCheckType(index, "number", "2", __name, __signature)
	        	end
	        end
	        if not __s then return false, __e end
	        ------------
	        --`Table` automatically passes all of the macro's arguments as its second argument
	        index = (type(index) == "number" and index) or #t.table
	
	        for key, value in ipairs(t.keys) do
	            if value == index then
	                table.remove(t.keys, key)
	            end
	        end
	
	        return true, table.remove(t.table, index)
	    end),
	    append = plume.obj.luaMacro("append", function (args, runtime, _, ip)
	        local __name      = "append"
	        local __signature = "`$append(table t, any ...items)`"
	        local __s, __e, self, t
	        __s, __e, t = plume.stdUnpackPositional(args, 1, math.huge,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        
	        local item
	        if #args.table == 2 then
	            item = args.table[2]
	        else
	            plume.warning.runtimeWarning(string.format("Deprecated `Table.append` usage.\nFrom edition 'Owl', `$Table.append` will take only one parameter.", name), "Do `$Table.append($t, $Table(a, b))` instead of `$Table.append($t, a, b)`", runtime, ip, {614, 654})
	            -- A very dirty fix to an outdated, but still-used, incorrect behavior.
	            item = plume.obj.table(0, 0)
	            for _, key in ipairs(args.keys) do
	                if key ~= "self" and key ~= 1 and args.table[key] ~= plume.obj.empty then
	                    local rkey = key
	                    if tonumber(key) then
	                        rkey = rkey - 1
	                    end
	                    item.table[rkey] = args.table[key]
	                    table.insert(item.keys, rkey)
	                end
	            end
	        end
	        table.insert(t.table, item)
	        table.insert(t.keys, #t.table)
	        return true
	    end),
	    join = plume.obj.luaMacro("join", function (args)
	        local __name      = "join"
	        local __signature = "`$join(string sep:$empty, string ...items)`"
	        local __s, __e, self = plume.stdUnpackPositional(args, 0, math.huge, __name, __signature)
	        local sep
	        if __s then __s, __e, self, sep = plume.stdUnpackNamed(args, {"self", "sep"}, __name, __signature) end
	        sep = sep or ""
	        if __s and sep then __s, __e, sep = plume.stdCheckType(sep, "string", "sep", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        if sep == plume.obj.empty then
	            sep = ""
	        end
	
	        local args = args.table
	        if args and #args == 1 and type(args[1]) == "table" and args[1].type == "table" then
	            return false, plume.error.joinErrorHint()
	        end
	
	        for i, value in ipairs(args) do
	            if type(value) ~= "number" and type(value) ~= "string" then
	                return false, plume.error.wrongArgTypeStd(i, "join", type(value), "string", "$table.join(string ...items)")
	            end
	        end
	
	        return pcall(table.concat, args, sep)
	    end),
	    removeKey = plume.obj.luaMacro("removeKey", function (args)
	        local __name      = "removeKey"
	        local __signature = "`$removeKey(table t, any key)`"
	        local __s, __e, self, t, key
	        __s, __e, t, key = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        key = tonumber(key) or key
	        local index = 0
	        for k, v in ipairs(t.keys) do
	            if v == key then
	                index = k
	                break
	            end
	        end
	
	        t.table[key] = nil
	        table.remove(t.keys, index)
	        return true
	    end),
	    hasKey = plume.obj.luaMacro("hasKey", function (args)
	        local __name      = "hasKey"
	        local __signature = "`$hasKey(table t, any key)`"
	        local __s, __e, self, t, key
	        __s, __e, t, key = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        key = tonumber(key) or key
	        for k, v in ipairs(t.keys) do
	            if v == key then
	                return true, true
	            end
	        end
	
	        return true, false
	    end),
	    find = plume.obj.luaMacro("find", function (args)
	        local __name      = "find"
	        local __signature = "`$find(table t, any x)`"
	        local __s, __e, self, t, x
	        __s, __e, t, x = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        for k, v in ipairs(t.keys) do
	            if t.table[v] == x then
	                return true, v
	            end
	        end
	        return true, nil
	    end),
	    findAll = plume.obj.luaMacro("findAll", function (args)
	        local __name      = "findAll"
	        local __signature = "`$findAll(table t, any x)`"
	        local __s, __e, self, t, x
	        __s, __e, t, x = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        local result = plume.obj.table(0, 0)
	        for k, v in ipairs(t.keys) do
	            if t.table[v] == x then
	                table.insert(result.table, v)
	                table.insert(result.keys, #result.table)
	            end
	        end
	
	        return true, result
	    end),
	    count = plume.obj.luaMacro("count", function (args)
	        local __name      = "count"
	        local __signature = "`$count(table t, ?named)`"
	        local __s, __e, self, t
	        __s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        local named
	        if __s then __s, __e, self, named = plume.stdUnpackNamed(args, {"self", "named"}, __name, __signature) end
	        named = named or false
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        if named then
	            local count = 0
	            for k, v in ipairs(t.keys) do
	                if not tonumber(v) then
	                    count = count + 1
	                end
	            end
	            return true, count
	        else
	            return true, #t.keys
	        end
	    end),
	    entry = plume.obj.luaMacro("entry", function (args)
	        local __name      = "entry"
	        local __signature = "`$entry(table t, any index)`"
	        local __s, __e, self, t, index
	        __s, __e, t, index = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        local key = t.keys[index]
	        local result = plume.obj.table(2, 0)
	        result.table[1] = key
	        result.table[2] = t.table[key]
	        result.keys = {1, 2}
	        
	        return true, result
	    end),
	
	    sort = plume.obj.luaMacro("sort", function (args)
	        local __name      = "sort"
	        local __signature = "`$sort(table t, macro compare:)`"
	        local __s, __e, self, t
	        __s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        local compare
	        if __s then __s, __e, self, compare = plume.stdUnpackNamed(args, {"self", "compare"}, __name, __signature) end
	        compare = compare or nil
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if __s and compare then __s, __e, compare = plume.stdCheckType(compare, "macro", "compare", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        if compare and #t.table > 1 then
	            if compare.positionalParamCount ~= 2 then
	                return false, string.format("Macro compare for `Table.sort` must take exactly '2' arguments, not '%i'.", compare.positionalParamCount)
	            end
	
	            local context = {
	                type         = "hostContext",
	                source       = t,
	                compare      = compare,
	                i            = 2,
	                j            = 1,
	                result       = {t.table[1]}, 
	                HOST_UPDATE  = sortUpdate,
	                HOST_NEXT    = sortNext
	            }
	            return true, context, true
	        else
	            table.sort(t.table)
	            return true
	        end
	    end),
	
	    copy = plume.obj.luaMacro("copy", function (args)
	        local __name      = "copy"
	        local __signature = "`$copy(table t)`"
	        local __s, __e, self, t
	        __s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, plume.stdUtils.copy(t)
	    end),
	
	    deepcopy = plume.obj.luaMacro("deepcopy", function (args)
	        local __name      = "deepcopy"
	        local __signature = "`$deepcopy(table t)`"
	        local __s, __e, self, t
	        __s, __e, t = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and t then __s, __e, t = plume.stdCheckType(t, "table", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, plume.stdUtils.copy(t, {})
	    end),
	
	    sum = plume.obj.luaMacro("sum", function (args)
	        local __name      = "sum"
	        local __signature = "`$sum(number ...numbers)`"
	        local __s, __e, self = plume.stdUnpackPositional(args, 0, math.huge, __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and numbers then __s, __e, numbers = plume.stdCheckType(numbers, "number", "1", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        local r = 0
	        for _, x in ipairs(numbers) do
	            r = r + x
	        end
	        return true, r
	    end)
	}
	
	plume.std.Table.meta = plume.obj.quickTable{
	    validate = plume.obj.luaMacro ("call", function (args)
	        local __name      = "call"
	        local __signature = "`$call(any x)`"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        local t = type(x) == "table" and x.type or  type(x)
	        if t ~= "table" then
	            return false, string.format("Cannot convert '%s' to a table.", t)
	        else
	            return true, x
	        end
	    end)
	}
	
	local createDate, createDuration
	
	local function getType(x)
		return type(x) == "table" and x.table.type or type(x)
	end
	
	local function convert(t, v)
		local r
		if t == "number" or t == "string" and tonumber(v) then
			r = tonumber(v)
		elseif t == "Duration" then
			r = v.value
		elseif t == "Date" then
			r = v.table.timestamp
		else
			return false, string.format("Cannot do arithmetic on '%s' value.", t)
		end
	
		return true, r
	end
	
	local ddadd = plume.obj.luaMacro("add", function (args)
		local x = args.table[1]
		local y = args.table[2]
	
		local tx = getType(x)
		local ty = getType(y)
	
		local success, vx = convert(tx, x)
		if not success then
			return success, vx
		end
		local success, vy = convert(ty, y)
		if not success then
			return success, vy
		end
	
		local result = vx + vy
	
		if tx ~= "Date" and ty ~= "Date" then
			return createDuration(result)
		else
			return createDate({timestamp=result})
		end
	end)
	
	local ddsub = plume.obj.luaMacro("sub", function(args)
		local x = args.table[1]
		local y = args.table[2]
	
		local tx = getType(x)
		local ty = getType(y)
	
		local success, vx = convert(tx, x)
		if not success then
			return success, vx
		end
		local success, vy = convert(ty, y)
		if not success then
			return success, vy
		end
	
		local result = vx - vy
	
		if tx ~= "Date" and ty ~= "Date" then
			return createDuration(result)
		else
			return createDate({timestamp=result})
		end
	end)
	
	local ddmul = plume.obj.luaMacro("mul", function(args)
		local x = args.table[1]
		local y = args.table[2]
	
		local tx = getType(x)
		local ty = getType(y)
	
		if tx == "Date" or ty == "Date" then
			return false, "Cannot multiply a 'Date' value."
		end
	
		local success, vx = convert(tx, x)
		if not success then
			return success, vx
		end
		local success, vy = convert(ty, y)
		if not success then
			return success, vy
		end
	
		local result = vx * vy
	
		return createDuration(result)
	end)
	
	local dddiv = plume.obj.luaMacro("div", function(args)
		local x = args.table[1]
		local y = args.table[2]
	
		local tx = getType(x)
		local ty = getType(y)
	
		if tx == "Date" or ty == "Date" then
			return false, "Cannot divide a 'Date' value."
		end
	
		local success, vx = convert(tx, x)
		if not success then
			return success, vx
		end
		local success, vy = convert(ty, y)
		if not success then
			return success, vy
		end
	
		local result = vx / vy
	
		return createDuration(result)
	end)
	
	
	function createDate (args)
		local time = plume.obj.table(0, 0)
		
		time.keys = {
			"timestamp",
			"locale",
			"zone",
			"type"
		}
	
		function time:updateTimestamp(args)
			self.table.timestamp = os.time({
				year   = args.year or 1970,
				month  = args.month or 1,
				day    = args.day or 1
			})
			if self.table.timestamp then
				return true
			else
				return false, "Cannot make a Date frome these parameters."
			end
		end
	
		function time:getFromTimestamp()
			local timestamp   = self.table.timestamp
			return {
				year   = tonumber(os.date("%Y", timestamp)),
				month  = tonumber(os.date("%m", timestamp)),
				day    = tonumber(os.date("%d", timestamp)),
				hour   = tonumber(os.date("%H", timestamp)),
				minute = tonumber(os.date("%M", timestamp)),
				second = tonumber(os.date("%S", timestamp))
			}
		end
	
		time.table.type      = "Date"
	
		local success, result = true
		if args.timestamp and args.timestamp ~= 0 then
			time.table.timestamp = args.timestamp
		else
			success, result = time:updateTimestamp(args)
		end
	
		if not success then
			return success, result
		end
	
		time.meta = plume.obj.quickTable{
			tostring = plume.obj.luaMacro ("tostring", function(args)
				local self = args.table.self
				return true, os.date("%x", self.table.timestamp)
			end),
			setindex = plume.obj.luaMacro ("setindex", function(args)
				local self   = args.table.self
				local key    = args.table[1]
				local value  = args.table[2]
				local values = self:getFromTimestamp()
	
				if not values[key] then
					return true, value
				end
	
				values[key] = value
				time:updateTimestamp(values)
	
				return true
			end),
			getindex = plume.obj.luaMacro ("getindex", function(args)
				local self = args.table.self
				local key = args.table[1]
				local values = self:getFromTimestamp()
	
				if not values[key] then
					return false, string.format("Unregistered key '%s'", key)
				end
				return true, values[key]
			end),
			add = ddadd,
			sub = ddsub,
			mul = ddmul,
			div = dddiv,
			eq = plume.obj.luaMacro("eq", function(args)
				local x = args.table[1]
				local y = args.table[2]
	
				local tx = getType(x)
				local ty = getType(y)
	
				if tx ~= "Date" or ty ~= "Date" then
					return true, false
				end
	
				return true, x.table.timestamp == y.table.timestamp
			end),
			lt = plume.obj.luaMacro("lt", function(args)
				local x = args.table[1]
				local y = args.table[2]
	
				local tx = getType(x)
				local ty = getType(y)
	
				if tx ~= "Date" or ty ~= "Date" then
					return false, string.format("Cannot compare 'Date' and '%s'", (tx ~= "Date" and tx or ty))
				end
	
				return true, x.table.timestamp < y.table.timestamp
			end)
		}
		
		return true, time
	end
	
	function createDuration(s)
		local duration = plume.obj.table(0, 0)
		duration.value = s
	
		duration.keys = {"type"}
	
		duration.table.type = "Duration"
	
		duration.meta = plume.obj.table(0, 0)
		duration.meta.keys = {"tostring", "setindex", "getindex", "add", "sub", "mul", "div"}
		duration.meta.table.tostring = plume.obj.luaMacro ("tostring", function(args)
			local self = args.table.self
			return true, self.value
		end)
		duration.meta.table.setindex = plume.obj.luaMacro ("setindex", function(args)
			local self   = args.table.self
			local key    = args.table[1]
			
			return false, "Cannot edit 'duration' fields."
		end)
		duration.meta.table.getindex = plume.obj.luaMacro ("getindex", function(args)
			local self = args.table.self
			local key = args.table[1]
			
			if key == "day" then
				return true, self.value / 86400
			elseif key == "hour" then
				return true, self.value / 3600
			elseif key == "minute" then
				return true, self.value / 60
			elseif key == "second" then
				return true, self.value
			end
	
			if not values[key] then
				return false, string.format("Unregistered key '%s'", key)
			end
		end)
	
		duration.meta.table.add = ddadd
		duration.meta.table.sub = ddsub
		duration.meta.table.mul = ddmul
		duration.meta.table.div = dddiv
	
		duration.meta.table.eq = plume.obj.luaMacro("eq", function(args)
			local x = args.table[1]
			local y = args.table[2]
	
			local tx = getType(x)
			local ty = getType(y)
	
			if tx ~= "Duration" or ty ~= "Duration" then
				return true, false
			end
	
			return true, x.value == y.value
		end)
	
		duration.meta.table.lt = plume.obj.luaMacro("lt", function(args)
			local x = args.table[1]
			local y = args.table[2]
	
			local tx = getType(x)
			local ty = getType(y)
	
			if tx ~= "Duration" or ty ~= "Duration" then
				return false, string.format("Cannot compare 'Duration' and '%s'", (tx ~= "Duration" and tx or ty))
			end
	
			return true, x.value < y.value
		end)
	
		return true, duration
	end
	
	local function ignoreSuccess(x, y)
		return y
	end
	
	plume.std.Time = plume.obj.quickTable{
		date = plume.obj.luaMacro("date", function(args)
			local __name      = "add"
		local __signature = "`$add(number year: 0, number month: 0, number day: 0, number year: 0, number year: 0, number year: 0, string zone:, string locale:, number timestamp: 0)`"
		local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
		local year, month, day, year, year, year, zone, locale, timestamp
		if __s then __s, __e, self, year, month, day, year, year, year, zone, locale, timestamp = plume.stdUnpackNamed(args, {"self", "year", "month", "day", "year", "year", "year", "zone", "locale", "timestamp"}, __name, __signature) end
		year = year or nil
		month = month or nil
		day = day or nil
		year = year or nil
		year = year or nil
		year = year or nil
		zone = zone or nil
		locale = locale or nil
		timestamp = timestamp or nil
		if __s and year then __s, __e, year = plume.stdCheckType(year, "number", "year", __name, __signature) end
		if __s and month then __s, __e, month = plume.stdCheckType(month, "number", "month", __name, __signature) end
		if __s and day then __s, __e, day = plume.stdCheckType(day, "number", "day", __name, __signature) end
		if __s and year then __s, __e, year = plume.stdCheckType(year, "number", "year", __name, __signature) end
		if __s and year then __s, __e, year = plume.stdCheckType(year, "number", "year", __name, __signature) end
		if __s and year then __s, __e, year = plume.stdCheckType(year, "number", "year", __name, __signature) end
		if __s and zone then __s, __e, zone = plume.stdCheckType(zone, "string", "zone", __name, __signature) end
		if __s and locale then __s, __e, locale = plume.stdCheckType(locale, "string", "locale", __name, __signature) end
		if __s and timestamp then __s, __e, timestamp = plume.stdCheckType(timestamp, "number", "timestamp", __name, __signature) end
		if not __s then return false, __e end
		------------
			return createDate(args)
		end),
		
		duration = plume.obj.luaMacro("duration", function (args)
			local __name      = "duration"
			local __signature = "`$duration(number seconds)`"
			local __s, __e, self, seconds
			__s, __e, seconds = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and seconds then __s, __e, seconds = plume.stdCheckType(seconds, "number", "1", __name, __signature) end
			if not __s then return false, __e end
			------------
			return createDuration(seconds)
		end),
	
		now = plume.obj.luaMacro("now", function (args)
			local __name      = "now"
			local __signature = "`$now()`"
			local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if not __s then return false, __e end
			------------
			return createDate({timestamp=os.time()})
		end),
	
		SECOND = ignoreSuccess(createDuration(1)),
		MINUTE = ignoreSuccess(createDuration(60)),
		DAY    = ignoreSuccess(createDuration(86400)),
		WEEK   = ignoreSuccess(createDuration(604800))
	}
	
	
	function plume.stdUnpackPositional (args, minArgs, maxArgs, name, signature)
		if #args.table < minArgs or #args.table > maxArgs then
			return false, plume.error.wrongArgsCountStd(
					name, #args.table, minArgs, maxArgs, signature
				)
		end
	
		return true, nil, unpack(args.table)
	end
	
	function plume.stdUnpackNamed(args, nameds, name, signature)
		local result = {}
	
		for _, key in ipairs(nameds) do
			nameds[key] = true
			if args.table[key] then
				table.insert(result, args.table[key])
			else
				table.insert(result, false)
			end
		end
	
		for _, key in ipairs(args.keys) do
			if not tonumber(key) then
				if nameds and nameds[key] then
					table.insert(result, args.table[key])
				else
					return false, plume.error.unknownParameterStd(key, name, signature)
				end
			end
		end
	
	
		return true, nil, unpack(result)
	end
	
	function plume.stdCheckType(arg, expected, argName, name, signature)
		local given = type(arg)
		if type(arg) == "table" and arg.type then
			if expected ~= "table" and arg.subtype then
				given = arg.subtype
			else
				given = arg.type
			end
		end
		if given == "luaMacro" or given == "stdMacro" then
			given = "macro"
		end
	
		if given == "string" and expected == "number" then
			if tonumber(arg) then
				arg = tonumber(arg)
				given = "number"
			end
		elseif given == "number" and expected == "string" then
			arg = tostring(arg)
			given = "string"
		end
	
		if given == expected then
			return true, nil, arg
		else
			return false, plume.error.wrongArgTypeStd(
				argName, name, given, expected, signature
			), arg
		end
	end
	
	plume.stdVM = {}
	local function registerLuaStdFunction(name, minArgs, maxArgs)
		if not minArgs then
			minArgs = 0
		end
		if not maxArgs then
			maxArgs = minArgs
		end
	
		plume.stdVM[name] = {
			type = "stdMacro",
			name = name,
			opcode = plume.ops_count,
			minArgs = minArgs,
			maxArgs = maxArgs
		}
		
		local opName = "STD_" .. name:upper()
		plume.ops[opName] = plume.ops_count
		plume.ops_names = plume.ops_names .. " " .. opName
		plume.ops_count = plume.ops_count + 1
	
	end
	
	registerLuaStdFunction("len", 1)
	registerLuaStdFunction("type", 1)
	registerLuaStdFunction("seq", 1, 3)
	registerLuaStdFunction("items", 1)
	registerLuaStdFunction("enumerate", 1)
	registerLuaStdFunction("import", 1)
	
	for name, obj in pairs(plume.stdVM) do
	    plume.std[name] = obj
	end
end
