--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]


-- generated by make-std.lua

return function(plume)
	
	
	plume.stdio = {}
	function plume.stdio.write(path, content, append)
		local mode = append and "a" or "w"
		local file = io.open(path, mode)
			if not file then
				return false, "Cannot write file '" .. path .. "'."
			end
			file:write(content)
		file:close()
		return true
	end
	
	function plume.stdio.read(path)
		local file = io.open(path)
			if not file then
				return false, "Cannot read file '" .. path .. "'."
			end
			local content = file:read("*a")
		file:close()
		return true, content
	end
	    
	plume.std.print = plume.obj.luaMacro("print", function (args)
	    local result = {}
	    for _, x in ipairs(args.table) do
	        table.insert(result, plume.repr(x, nil, args.table.pretty))
	    end
	    print(table.unpack(result))
	    return true
	end)
	
	plume.std.help = plume.obj.luaMacro("help", function (args)
	    local __name      = "print"
	    local __signature = "macro macro"
	    local __s, __e, self, macro
	    __s, __e, macro = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if __s and macro then __s, __e, macro = plume.stdCheckType(macro, "macro", "macro", __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    print("macro " .. (macro.debugMacroName or macro.name) .. "\n    " .. macro.doc:gsub('\n', '\n    ') or "")
	    return true
	end)
	
	-- io
	plume.std.write = plume.obj.luaMacro("write", function (args)
	    local __name      = "write"
	    local __signature = "string filename, string content, ?append"
	    local __s, __e, self, filename, content
	    __s, __e, filename, content = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
	    local append
	    if __s then __s, __e, self, append = plume.stdUnpackNamed(args, {"self", "append"}, __name, __signature) end
	    append = append or false
	    if __s and filename then __s, __e, filename = plume.stdCheckType(filename, "string", "filename", __name, __signature) end
	    if __s and content then __s, __e, content = plume.stdCheckType(content, "string", "content", __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    return plume.stdio.write(filename, content, append)
	end)
	
	plume.std.read = plume.obj.luaMacro("read", function (args)
	    local __name      = "read"
	    local __signature = "string filename"
	    local __s, __e, self, filename
	    __s, __e, filename = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if __s and filename then __s, __e, filename = plume.stdCheckType(filename, "string", "filename", __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    return plume.stdio.read(filename)
	end)
	
	plume.std.rawset = plume.obj.luaMacro("rawset", function (args)
	    local __name      = "rawset"
	    local __signature = "table obj, string key, any value"
	    local __s, __e, self, obj, key, value
	    __s, __e, obj, key, value = plume.stdUnpackPositional(args, 3, 3,  __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if __s and obj then __s, __e, obj = plume.stdCheckType(obj, "table", "obj", __name, __signature) end
	    if __s and key then __s, __e, key = plume.stdCheckType(key, "string", "key", __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	
	    if not obj.table[key] then
	        table.insert(obj.keys, key)
	    end
	    obj.table[key] = value
	    return true
	end)
	
	plume.std.repr = plume.obj.luaMacro("repr", function (args)
	    local __name      = "repr"
	    local __signature = "any obj, ?pretty"
	    local __s, __e, self, obj
	    __s, __e, obj = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	    local pretty
	    if __s then __s, __e, self, pretty = plume.stdUnpackNamed(args, {"self", "pretty"}, __name, __signature) end
	    pretty = pretty or false
	    if not __s then return false, __e end
	    ------------
	    return true, plume.repr(obj, nil, pretty)
	end)
	
	plume.std.min = plume.obj.luaMacro("min", function (args)
	    local __name      = "min"
	    local __signature = "number ...numbers"
	    local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, 0, __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    return true, math.min(unpack(args.table))
	end)
	plume.std.max = plume.obj.luaMacro("max", function (args)
	    local __name      = "max"
	    local __signature = "number ...numbers"
	    local __s, __e, self = plume.stdUnpackPositional(args, 0, 0, 0, __name, __signature)
	    if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	    if not __s then return false, __e end
	    ------------
	    return true, math.max(unpack(args.table))
	end)
	
	plume.std.List = plume.obj.table(0, 0)
	plume.std.List.meta = plume.obj.quickTable{
	    call = plume.obj.luaMacro ("call", function(args)
	        local result = plume.obj.table(0, 0)
	        local t = args.table[1]
	        for k, v in ipairs(t.table) do
	            table.insert(result.keys, k)
	            table.insert(result.table, v)
	        end
	        return true, result
	    end),
	    validate = plume.obj.luaMacro ("validate", function(args)
	        local t = args.table[1]
	        for _, k in ipairs(t.keys) do
	            if not tonumber(k) then
	                return false, string.format("Received extra named argument '%s', but extra arguments must be positional.", k)
	            end
	        end
	
	        return true, args
	    end)
	}
	
	plume.std.Map = plume.obj.table(0, 0)
	plume.std.Map.meta = plume.obj.quickTable{
	    call = plume.obj.luaMacro ("call", function(args)
	        local result = plume.obj.table(0, 0)
	        local t = args.table[1]
	        for _, k in ipairs(t.keys) do
	            if not tonumber(k) then
	                table.insert(result.keys, k)
	                result.table[k] = t.table[k]
	            end
	        end
	        return true, result
	    end),
	    validate = plume.obj.luaMacro ("validate", function(args)
	        local t = args.table[1]
	        for _, k in ipairs(t.keys) do
	            if tonumber(k) then
	                return false, "Received an extra positional argument, but extra arguments must be named."
	            end
	        end
	
	        return true, args
	    end)
	}
	
	plume.std.Math = plume.obj.quickTable{
	    sin = plume.obj.luaMacro("sin", function (args)
	        local __name      = "sin"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.sin(x)
	    end),
	    cos = plume.obj.luaMacro("cos", function (args)
	        local __name      = "cos"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.cos(x)
	    end),
	    tan = plume.obj.luaMacro("tan", function (args)
	        local __name      = "tan"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.tan(x)
	    end),
	    asin =  plume.obj.luaMacro("asin", function (args)
	        local __name      = "asin"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.asin(x)
	    end),
	    acos =  plume.obj.luaMacro("acos", function (args)
	        local __name      = "acos"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.acos(x)
	    end),
	    atan =  plume.obj.luaMacro("atan", function (args)
	        local __name      = "atan"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.atan(x)
	    end),
	    atan2 =  plume.obj.luaMacro("atan2", function (args)
	        local __name      = "atan2"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.atan2(x, y)
	    end),
	    sinh =  plume.obj.luaMacro("sinh", function (args)
	        local __name      = "sinh"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.sinh(x)
	    end),
	    cosh =  plume.obj.luaMacro("cosh", function (args)
	        local __name      = "cosh"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.cosh(x)
	    end),
	    tanh =  plume.obj.luaMacro("tanh", function (args)
	        local __name      = "tanh"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.tanh(x)
	    end),
	    log =  plume.obj.luaMacro("log", function (args)
	        local __name      = "log"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.log(x)
	    end),
	    log10 =  plume.obj.luaMacro("log10", function (args)
	        local __name      = "log10"
	        local __signature = "number x"
	        local __s, __e, self, x
	        __s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, math.log10(x)
	    end),
	    pi   = math.pi,
	    e    = math.exp(1),
	    huge = math.huge
	}
	
	plume.formatNumber = function(x, format, locale, thousandsSeparator, decimalSeparator, thousandthsSeparator)
		if thousandsSeparator == plume.obj.empty then
			thousandsSeparator = nil
		end
		if thousandthsSeparator == plume.obj.empty then
			thousandthsSeparator = nil
		end
		if not format or format == plume.obj.empty then
			format = "%s"
		end
	
		local result = string.format(format, x)
		if locale then
			local integerPart, decimalPart
			if result:gmatch('%.') then
				integerPart = result:match('^[^%.]+')
				decimalPart = result:match('%.([^%.]+)')
			else
				integerPart = result
			end
	
			if locale == "en" or locale == "us" then
				thousandsSeparator = ","
				decimalSeparator  = "."
			elseif locale == "fr" then
				thousandsSeparator    = " "
				decimalSeparator     = ","
				thousandthsSeparator = " "
			elseif locale == "custom" then
				thousandsSeparator    = thousandsSeparator or nil
				decimalSeparator     = decimalSeparator or "."
				thousandthsSeparator = thousandthsSeparator or nil
			elseif locale then
				return false, "Unknown localization format '" .. locale .. "'."
			end
	
			if thousandsSeparator then
				thousandsSeparator = thousandsSeparator:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
				integerPart = integerPart:gsub("(.)(...)$", "%1"..thousandsSeparator.."%2")
				for i=1, #integerPart do
					integerPart = integerPart:gsub("([0-9])([0-9][0-9][0-9])"..thousandsSeparator, "%1"..thousandsSeparator.."%2"..thousandsSeparator)
				end
			end
			result = integerPart
	
			if decimalPart then
				if thousandthsSeparator then
					thousandthsSeparator = thousandthsSeparator:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
					decimalPart = decimalPart:gsub("^([0-9][0-9][0-9])([0-9])", "%1"..thousandthsSeparator.."%2")
					for i=1, #integerPart do
						decimalPart = decimalPart:gsub(thousandthsSeparator.."([0-9][0-9][0-9])([0-9])", "%1"..thousandthsSeparator.."%2"..thousandthsSeparator)
					end
				end
	
				result = result .. decimalSeparator .. decimalPart
			end
		end
	
		return true, result
	end
	
	plume.std.Number = plume.obj.quickTable{
		-- Manipulations
		floor = plume.obj.luaMacro("floor", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "floor"
			local __signature = "number x, number digit:0"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local digit
			if __s then __s, __e, self, digit = plume.stdUnpackNamed(args, {"self", "digit"}, __name, __signature) end
			digit = digit or 0
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
			if __s and digit then __s, __e, digit = plume.stdCheckType(digit, "number", "digit", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.floor(x*10^digit)*10^-digit
		end),
		ceil = plume.obj.luaMacro("ceil", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "ceil"
			local __signature = "number x, number digit:0"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local digit
			if __s then __s, __e, self, digit = plume.stdUnpackNamed(args, {"self", "digit"}, __name, __signature) end
			digit = digit or 0
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
			if __s and digit then __s, __e, digit = plume.stdCheckType(digit, "number", "digit", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.ceil(x*10^digit)*10^-digit
		end),
		round = plume.obj.luaMacro("round", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "round"
			local __signature = "number x, number digit:0"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local digit
			if __s then __s, __e, self, digit = plume.stdUnpackNamed(args, {"self", "digit"}, __name, __signature) end
			digit = digit or 0
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
			if __s and digit then __s, __e, digit = plume.stdCheckType(digit, "number", "digit", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.floor(x*10^digit + 0.5)*10^-digit
		end),
		abs = plume.obj.luaMacro("abs", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "abs"
			local __signature = "number x"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.abs(x)
		end),
		clamp = plume.obj.luaMacro("clamp", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "clamp"
			local __signature = "number x, number min, number max"
			local __s, __e, self, x, min, max
			__s, __e, x, min, max = plume.stdUnpackPositional(args, 3, 3,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
			if __s and min then __s, __e, min = plume.stdCheckType(min, "number", "min", __name, __signature) end
			if __s and max then __s, __e, max = plume.stdCheckType(max, "number", "max", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, math.min(max, math.max(min, x))
		end),
		format = plume.obj.luaMacro("format", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "format"
			local __signature = "number x, string format, string locale:, string thousandsSeparator:, string decimalSeparator:, string thousandthsSeparator:"
			local __s, __e, self, x, format
			__s, __e, x, format = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local locale, thousandsSeparator, decimalSeparator, thousandthsSeparator
			if __s then __s, __e, self, locale, thousandsSeparator, decimalSeparator, thousandthsSeparator = plume.stdUnpackNamed(args, {"self", "locale", "thousandsSeparator", "decimalSeparator", "thousandthsSeparator"}, __name, __signature) end
			locale = locale or nil
			thousandsSeparator = thousandsSeparator or nil
			decimalSeparator = decimalSeparator or nil
			thousandthsSeparator = thousandthsSeparator or nil
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
			if __s and format then __s, __e, format = plume.stdCheckType(format, "string", "format", __name, __signature) end
			if not __s then return false, __e end
			------------
			return plume.formatNumber(
				x, format, locale, thousandsSeparator, decimalSeparator, thousandthsSeparator
			)
		end),
		localize = plume.obj.luaMacro("format", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "format"
			local __signature = "number x, string locale"
			local __s, __e, self, x, locale
			__s, __e, x, locale = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
			if __s and locale then __s, __e, locale = plume.stdCheckType(locale, "string", "locale", __name, __signature) end
			if not __s then return false, __e end
			------------
			return plume.formatNumber(x, "%s", locale)
		end),
	
		-- Test
		sign = plume.obj.luaMacro("sign", function (args)
			if args.table.self and args.table.self ~= plume.std.Number then table.insert(args.table, 1, args.table.self) end
			local __name      = "sign"
			local __signature = "number x"
			local __s, __e, self, x
			__s, __e, x = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and x then __s, __e, x = plume.stdCheckType(x, "number", "x", __name, __signature) end
			if not __s then return false, __e end
			------------
			if x>0 then
				return true, 1
			elseif x<0 then
				return true, -1
			else
				return true, 0
			end
		end)
	}
	
	plume.std.Number.meta = plume.obj.quickTable {
		call = plume.obj.luaMacro("Number", function(args)
			local x = args.table[1]
			if x == plume.obj.empty then
				return false, "Cannot convert empty into number"
			elseif type(x) == "number" then
				return true, x
			elseif tonumber(x) then
				return true, tonumber(x)
			else
			   return false, string.format("Cannot convert %s into number", type(x))
			end
		end)
	}
	
	plume.std.os = plume.obj.quickTable {
	    getEnv = plume.obj.luaMacro("getEnv", function (args)
	        local __name      = "getEnv"
	        local __signature = "string name"
	        local __s, __e, self, name
	        __s, __e, name = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and name then __s, __e, name = plume.stdCheckType(name, "string", "name", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	        return true, os.getenv(name)
	    end),
	
	    -- Very basic implementation
	    execute = plume.obj.luaMacro("execute", function (args)
	        local __name      = "execute"
	        local __signature = "string command"
	        local __s, __e, self, command
	        __s, __e, command = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
	        if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
	        if __s and command then __s, __e, command = plume.stdCheckType(command, "string", "command", __name, __signature) end
	        if not __s then return false, __e end
	        ------------
	    	local success, result = pcall(function()
	    	    local h = io.popen(command)
	    		if not h then
	    			return nil
	    		end
	    		local r = h:read("*a")
	    		h:close()
	    		return r
	    	end)
	        return success, result
	    end)
	}
	
	local lfs = require"lfs"
	
	local function mkdirs(path, isFile)
		local fullPath = ""
		path = path:gsub('\\', '/')
		for frag in path:gmatch('[^/]+') do
			if fullPath ~= "" or path:sub(1, 1) == "/" then
				fullPath = fullPath .. "/"
			end
			fullPath = fullPath .. frag
			if isFile and path == fullPath then
				break
			end
	
			local attr = lfs.attributes(fullPath)
			if not attr then
				local success, result = lfs.mkdir(fullPath)
				if not success then
					return false, result
				end
			end
		end
		return true
	end
	
	local function makePath(path)
		local obj = plume.obj.quickTable{
			path = path or lfs.currentdir (),
			type = "Path",
			isFile = plume.obj.luaMacro ("isFile", function (args)
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
	
				if not attr then
					return true, false
				end
	
				return true, attr.mode == "file"
			end),
			isDirectory = plume.obj.luaMacro ("isDirectory", function(args)
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
	
				if not attr then
					return true, false
				end
	
				return true, attr.mode == "directory"
			end),
			exists = plume.obj.luaMacro ("exists", function(args)
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
				return true, attr ~= nil
			end),
			make = plume.obj.luaMacro ("make", function(args)
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
	
				if attr then
					return false, string.format("'%s' already exists, cannot create it.", path)
				end
	
				return mkdirs(path)
			end),
			remove = plume.obj.luaMacro ("remove", function(args)
				local path = args.table.self.table.path
				local attr = lfs.attributes(path)
	
				if not attr then
					return false, string.format("'%s' don't exists, cannot remove it.", path)
				end
	
				if attr.mode == "file" then
					return os.remove(path)
				else
					return lfs.rmdir(path)
				end
	
			end),
			move = plume.obj.luaMacro ("move", function(args)
				local path = args.table.self.table.path
				local newpath = args.table[1]
				local attr = lfs.attributes(path)
	
				if not attr then
					return false, string.format("'%s' don't exists, cannot move it.", path)
				end
	
				args.table.self.table.path = newpath
				return os.rename(path, newpath)
			end),
			copy = plume.obj.luaMacro ("copy", function(args)
				local path = args.table.self.table.path
				local newpath = args.table[1]
	
				local src = io.open(path)
				if not src then
					return false, string.format("Cannot read '%s'", src)
				end
				local dest = io.open(newpath, "w")
				if not dest then
					return false, string.format("Cannot write '%s'", dest)
				end
	
				dest:write(src:read("*a"))
				src:close()
				dest:close()
	
				return makePath(newpath)
			end),
	
			getParent = plume.obj.luaMacro ("getParent", function(args)
				local path = args.table.self.table.path
	
				if path:match('[/\\]') then
					return makePath(path:gsub('[/\\][^/\\]*$', ''))
				else
					return false, "Cannot return parent of root"
				end
			end),
			getName = plume.obj.luaMacro ("getName", function(args)
				local path = args.table.self.table.path
				return true, path:match('[^/\\]*$')
			end),
			read = plume.obj.luaMacro ("read", function(args)
				local path = args.table.self.table.path
				return plume.stdio.read(path)
			end),
			write = plume.obj.luaMacro ("write", function(args)
				local path = args.table.self.table.path
				local success, result = mkdirs(path, true)
				if not success then
					return false, result
				end
	
				local append = args.table.append
				return plume.stdio.write(path, table.concat(args.table), append)
			end),
			touch = plume.obj.luaMacro ("touch", function(args)
				local path = args.table.self.table.path
				local success, result = mkdirs(path, true)
				if not success then
					return false, result
				end
	
				local file = io.open(path, "w")
				if not file then
					return false, string.format("Cannot touch '%s'", path)
				end
				file:close()
				return true
			end),
			getChildren = plume.obj.luaMacro ("getChildren", function(args)
				local path = args.table.self.table.path
				local result = plume.obj.table(0, 0)
	
				for child in lfs.dir(path) do
					if child ~= "." and child ~= ".." then
						local _, childPath = makePath(path.."/"..child)
						table.insert(result.table, childPath)
						table.insert(result.keys, #result.table)
					end
				end
				return true, result
			end),
			walk = plume.obj.luaMacro ("walk", function(args)
				local path = args.table.self.table.path
				local result = plume.obj.table(0, 0)
	
				local toExplore = {path}
				local pos = 1
				while pos <= #toExplore do
					local path = toExplore[pos]
					pos = pos + 1
	
					for child in lfs.dir(path) do
						if child ~= "." and child ~= ".." then
							local childPath = path.."/"..child
							local _, childPathObj = makePath(childPath)
							table.insert(result.table, childPathObj)
							table.insert(result.keys, #result.table)
	
							table.insert(toExplore, childPath)
						end
					end
				end
				return true, result
			end)
		}
	
		local function div(x1, x2)
			local path1, path2
	
			if type(x1) == "string" then
				path1 = x1
			else
				path1 = x1.table.path
			end
	
			if type(x2) == "string" then
				path2 = x2
			else
				path2 = x2.table.path
			end
	
			return makePath(path1 .. "/" .. path2)
		end
	
		obj.meta = plume.obj.quickTable{
			tostring = plume.obj.luaMacro ("tostring", function(args)
				local path = args.table.self.table.path
				return true, path
			end),
	
			div = plume.obj.luaMacro ("div", function(args)
				return div(args.table[1], args.table[2])
			end)
		}
		
		return true, obj
	end
	
	table.insert(plume.std.os.keys, "Path")
	plume.std.os.table.Path = plume.obj.luaMacro("Path", function (args)
	    local __name      = "isFile"
				local __signature = "[string path]"
				local __s, __e, self, path
				__s, __e, path = plume.stdUnpackPositional(args, 0, 1,  __name, __signature)
				if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
				if __s and path then __s, __e, path = plume.stdCheckType(path, "string", "path", __name, __signature) end
				if not __s then return false, __e end
				------------
	    return makePath(path)
	end)
	
	-- plume.std.plume isn't loaded like other std table,
	-- but copied at runtime creation
	
	plume.std.plume = plume.obj.quickTable {
		doc = plume.obj.luaMacro("doc", function (args)
			local __name      = "doc"
			local __signature = "macro m"
			local __s, __e, self, m
			__s, __e, m = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and m then __s, __e, m = plume.stdCheckType(m, "macro", "m", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, "macro " .. (m.debugMacroName or m.name) .. "\n    " .. m.doc:gsub('\n', '\n    ') or ""
		end)
	}
	
	plume.std.Random = plume.obj.luaMacro("Random", function (args)
		local __name      = "Random"
		local __signature = "[number seed]"
		local __s, __e, self, seed
		__s, __e, seed = plume.stdUnpackPositional(args, 0, 1,  __name, __signature)
		if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
		if __s and seed then __s, __e, seed = plume.stdCheckType(seed, "number", "seed", __name, __signature) end
		if not __s then return false, __e end
		------------
	    
	
	    function _deriveSeed(seed, index)
			seed = ((seed + index * 1234567) * 1103515245 + 12345) % 2147483647
			if seed==0 then
				return 1
			else
				return seed
			end
		end
		local state = _deriveSeed(args.table[1] or os.time(), 1)
	
	    function _random()
	    	state = ((state * 48271) % 2147483647)
			return (state / 2147483647)
	    end
	    function _random_range(a, b)
			return math.floor(_random() * (b-a+1) + a)
	    end
	
	    local function shuffle(t)
			for k=1, #t.table do
				local i = _random_range(1, #t.table)
				local j = _random_range(1, #t.table)
	
				t.table[i], t.table[j] = t.table[j], t.table[i]
			end
		end
	   	
	    local random = plume.obj.quickTable{
		    seed = plume.obj.luaMacro ("seed", function(args)
		    	state = _deriveSeed(args.table[1] or os.time(), 1)
		    	return true
			end),
		    choice = plume.obj.luaMacro ("choice", function(args)
		    	local t = args.table[1]
		    	return true, t.table[_random_range(1, #t.table)]
			end),
			pchoice = plume.obj.luaMacro ("pchoice", function(args)
				local t = args.table[1]
				local tw = 0
				for _, k in ipairs(t.keys) do
					local v = t.table[k]
					if type(v) == "number" then
						tw = tw + v
					end
				end
				local r = _random() * tw
				tw = 0
				for _, k in ipairs(t.keys) do
					local v = t.table[k]
					if type(v) == "number" then
						tw = tw + v
						if tw>=r then
							return true, k
						end
					end
				end
			end),
			shuffle = plume.obj.luaMacro ("shuffle", function(args)
				shuffle(args.table[1])
		    	return true
			end),
			sample = plume.obj.luaMacro ("sample", function(args)
				local t = args.table[1]
				local count = args.table[2]
				if count > #t.table then
					return false, string.format("Cannot give a '%i'-size sample of a table with '%i' element%s.",
						count, #t.table, "s" and #t.table>1 or "")
				end
				t = plume.stdUtils.copy(t)
				shuffle(t)
	
				for i=#t.table, count+1, -1 do
					for j, key in ipairs(t.keys) do
						if key==i then
		    				t.keys[j] = nil
		    				break
		    			end
					end
					t.table[i] = nil
				end
		    	return true, t
			end)
		}
		random.meta = plume.obj.quickTable{
			call = plume.obj.luaMacro ("call", function(args)
				if #args.table == 0 then
		        	return true, _random()
		        elseif #args.table == 1 then
		        	return true, _random_range(0, args.table[1])
		        elseif #args.table == 2 then
		        	return true, _random_range(args.table[1], args.table[2])
		        end
			end)
		}
	    
	    return true, random
	end)
	
	local function replaceUpdate(context)
		local s       = context.string
		local pos     = context.pos
		local pattern = context.pattern
		local acc     = context.acc
	
		local bpos, epos = s:sub(pos, -1):find(pattern)
	
		if bpos then
			context.PLUME_CALLBACK = context.macro
			table.insert(acc, s:sub(pos, pos+bpos-2))
			context.PLUME_CALLBACK_ARGS = {s:sub(pos+bpos-1, pos+epos-1)}
			context.pos = context.pos+epos
		else
			context.PLUME_CALLBACK = nil
			table.insert(acc, s:sub(pos, -1))
			context.pos = #s+1
			context.RETURN_VALUE = table.concat(acc)
		end
		return true
	end
	
	local function replaceNext(context, value)
		local t = type(value) == "table" and value.type or type(value)
		if t ~= "string" and t ~= "number" and t ~= "empty" then
			return false, string.format("Macro sub for `String.replace` must return a 'string' or a 'number', not a '%s'.", t)
		end
	
		if (type(value) ~= "table" or value.type ~= "empty") then
			table.insert(context.acc, value)
		end
		return true
	end
	
	plume.std.String = plume.obj.quickTable {
	
		-- Manipulation
		upper = plume.obj.luaMacro("upper", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "upper"
			local __signature = "string s"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, string.upper(s)
		end),
		lower = plume.obj.luaMacro("lower", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "lower"
			local __signature = "string s"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, string.lower(s)
		end),
	
		replace = plume.obj.luaMacro("replace", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "replace"
			local __signature = "string s, string pattern, string|macro sub, ?rich"
			local __s, __e, self, s, pattern, sub
			__s, __e, s, pattern, sub = plume.stdUnpackPositional(args, 3, 3,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "pattern", __name, __signature) end
			if __s and sub then
				__s, __e, sub = plume.stdCheckType(sub, "string", "sub", __name, __signature)
				if not __s then
					__s, __e, sub = plume.stdCheckType(sub, "macro", "sub", __name, __signature)
				end
			end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
				if type(sub) == "string" then
					sub = sub:gsub("%%", "%%%%")
				end
			end
	
			if type(sub) ~= "string" then
				if sub.positionalParamCount ~= 1 then
					return false, string.format("Macro sub for `String.replace` must take exactly '1' argument, not '%i'.", sub.positionalParamCount)
				end
	
				local context = {
					type         = "hostContext",
					string       = s,
					pattern      = pattern,
					pos          = 1,
					macro        = sub,
					acc          = {},
					HOST_UPDATE  = replaceUpdate,
					HOST_NEXT    = replaceNext
				}
				return true, context, true
			end
	
			return true, (s:gsub(pattern, sub))
		end),
	
		-- Tests
		isNumber = plume.obj.luaMacro("isNumber", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "isNumber"
			local __signature = "string s"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if not __s then return false, __e end
			------------
			if tonumber(s) then
				return true, true
			else
				return true, false
			end
		end),
	
		-- Normalization
		trim = plume.obj.luaMacro("trim", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "trim"
			local __signature = "string s"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, (s:gsub('^%s*', ''):gsub('%s*$', ''))
		end),
		rtrim = plume.obj.luaMacro("rtrim", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "rtrim"
			local __signature = "string s"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, (s:gsub('^%s*', ''))
		end),
		ltrim = plume.obj.luaMacro("ltrim", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "ltrim"
			local __signature = "string s"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, (s:gsub('%s*$', ''))
		end),
		collapse = plume.obj.luaMacro("collapse", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "collapse"
			local __signature = "string s"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, (s:gsub('%s+', ' '))
		end),
		dedent = plume.obj.luaMacro("dedent", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "dedent"
			local __signature = "string s"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if not __s then return false, __e end
			------------
			local firstIndent = s:match('^%s+')
			return true, (s:gsub('^'..firstIndent, ''):gsub('\n'..firstIndent, '\n'))
		end),
		indent = plume.obj.luaMacro("indent", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "indent"
			local __signature = "string s, string sep:\\t"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local sep
			if __s then __s, __e, self, sep = plume.stdUnpackNamed(args, {"self", "sep"}, __name, __signature) end
			sep = sep or "\t"
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and sep then __s, __e, sep = plume.stdCheckType(sep, "string", "sep", __name, __signature) end
			if not __s then return false, __e end
			------------
			return true, sep..s:gsub('\n', '\n'..sep)
		end),
	
		-- search
		find = plume.obj.luaMacro("find", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "find"
			local __signature = "string s, string pattern, ?rich"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "pattern", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			return true, (s:match(pattern) or plume.empty)
		end),
		contains = plume.obj.luaMacro("contains", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "contains"
			local __signature = "string s, string pattern, ?rich"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "pattern", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			if s:match(pattern) then
				return true, true
			else
				return true, false
			end
		end),
		startsWidth = plume.obj.luaMacro("startsWidth", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "startsWidth"
			local __signature = "string s, string pattern, ?rich"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "pattern", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			if s:match("^"..pattern) then
				return true, true
			else
				return true, false
			end
		end),
		endsWidth = plume.obj.luaMacro("endsWidth", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "endsWidth"
			local __signature = "string s, string pattern, ?rich"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "pattern", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			if s:match(pattern.."$") then
				return true, true
			else
				return true, false
			end
		end),
		count = plume.obj.luaMacro("count", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "count"
			local __signature = "string s, string pattern, ?rich"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "pattern", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			local count = 0
			for x in s:gmatch(pattern) do
				count = count + 1
			end
	
			return true, count
		end),
	
		-- table making
		split = plume.obj.luaMacro("split", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "split"
			local __signature = "string s, string sep:\\s, ?rich"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			local sep, rich
			if __s then __s, __e, self, sep, rich = plume.stdUnpackNamed(args, {"self", "sep", "rich"}, __name, __signature) end
			sep = sep or " "
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and sep then __s, __e, sep = plume.stdCheckType(sep, "string", "sep", __name, __signature) end
			if not __s then return false, __e end
			------------
			local t = plume.obj.table(0, 0)
	
			if not rich then
				sep = sep:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			local pos = 1
			for sub, _sep in s:gmatch('(.-)('..sep..")") do
				table.insert(t.table, sub)
				table.insert(t.keys, #t.table)
				pos = pos + #sub + #_sep
			end
	
			if pos <= #s then
				table.insert(t.table, s:sub(pos, -1))
				table.insert(t.keys, #t.table)
			end
	
			return true, t
		end),
		lines = plume.obj.luaMacro("lines", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "lines"
			local __signature = "string s"
			local __s, __e, self, s
			__s, __e, s = plume.stdUnpackPositional(args, 1, 1,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if not __s then return false, __e end
			------------
			local t = plume.obj.table(0, 0)
	
			local pos = 1
			for sub in s:gmatch('(.-)\n') do
				table.insert(t.table, sub)
				table.insert(t.keys, #t.table)
				pos = pos + #sub + 1
			end
	
			if pos <= #s then
				table.insert(t.table, s:sub(pos, -1))
				table.insert(t.keys, #t.table)
			end
	
			return true, t
		end),
		findAll = plume.obj.luaMacro("findAll", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "findAll"
			local __signature = "string s, string pattern, ?rich"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "pattern", __name, __signature) end
			if not __s then return false, __e end
			------------
	
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			local t = plume.obj.table(0, 0)
	
			for sub in s:gmatch(pattern) do
				table.insert(t.table, sub)
				table.insert(t.keys, #t.table)
			end
	
			return true, t
		end),
		partition = plume.obj.luaMacro("partition", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "partition"
			local __signature = "string s, string pattern, ?rich"
			local __s, __e, self, s, pattern
			__s, __e, s, pattern = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local rich
			if __s then __s, __e, self, rich = plume.stdUnpackNamed(args, {"self", "rich"}, __name, __signature) end
			rich = rich or false
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and pattern then __s, __e, pattern = plume.stdCheckType(pattern, "string", "pattern", __name, __signature) end
			if not __s then return false, __e end
			------------
			if not rich then
				pattern = pattern:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1")
			end
	
			local t = plume.obj.table(3, 0)
			t.keys = {1, 2, 3}
			t.table[1], t.table[2], t.table[3] = s:match("(.-)("..pattern..")(.+)")
	
			return true, t
		end),
	
		rep = plume.obj.luaMacro("rep", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "rep"
			local __signature = "string s, number count, string sep:$empty"
			local __s, __e, self, s, count
			__s, __e, s, count = plume.stdUnpackPositional(args, 2, 2,  __name, __signature)
			local sep
			if __s then __s, __e, self, sep = plume.stdUnpackNamed(args, {"self", "sep"}, __name, __signature) end
			sep = sep or ""
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and count then __s, __e, count = plume.stdCheckType(count, "number", "count", __name, __signature) end
			if __s and sep then __s, __e, sep = plume.stdCheckType(sep, "string", "sep", __name, __signature) end
			if not __s then return false, __e end
			------------
			count = tonumber(count)
			local result = {}
			for i=1, count do
				table.insert(result, s)
				if i<count then
					table.insert(result, sep)
				end
			end
	
			return true, table.concat(result)
		end),
	
		sub = plume.obj.luaMacro("sub", function (args)
			if args.table.self and args.table.self ~= plume.std.String then table.insert(args.table, 1, args.table.self) end
			local __name      = "sub"
			local __signature = "string s, number startpos, number endpos"
			local __s, __e, self, s, startpos, endpos
			__s, __e, s, startpos, endpos = plume.stdUnpackPositional(args, 3, 3,  __name, __signature)
			if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end
			if __s and s then __s, __e, s = plume.stdCheckType(s, "string", "s", __name, __signature) end
			if __s and startpos then __s, __e, startpos = plume.stdCheckType(startpos, "number", "startpos", __name, __signature) end
			if __s and endpos then __s, __e, endpos = plume.stdCheckType(endpos, "number", "endpos", __name, __signature) end
			if not __s then return false, __e end
			------------
			if epos == 1 then
				epos = #s
			end
	
			return true, s:sub(startpos, endpos)
		end)
	}
end
