--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

-- Optimize engine.lua to performances
-- Thanks for thenumbernine lua-parser lib.

package.path =  "build-tools/?.lua;build-tools/thenumbernine/?.lua;build-tools/thenumbernine/ext/?.lua;;build-tools/thenumbernine/parser/?.lua;;build-tools/thenumbernine/template/?.lua;" .. package.path

local ast = require "parser.lua.ast"
local tolua = require 'ext.tolua'
local optimizer = require"luaOptimizer"
local cleaner = require"luaCleaner"
local beautifier = require "luaBeautifier"

local function printTable(t)
	print(tolua(t))
end

local debug = false

require "make-engine" -- Compile base file
local tree

if debug then
	tree = optimizer.loadCode([[
do
    mainStackPointer = mainStackPointer + 1
    mainStack[mainStackPointer] = constants[arg2]
end
]], false)
else
	tree = optimizer.loadCode('plume-data/engine/engine.lua', true)
end

-- printTable(tree)

tree:traverse(optimizer.inlineRequire)
tree:traverse(optimizer.renameRun)
tree:traverse(optimizer.saveFunctionsToInline)
tree:traverse(optimizer.inlineFunctions)
tree:traverse(optimizer.applyInsertBefore)
tree:traverse(optimizer.applyInsertExprs)
tree:traverse(optimizer.inlineIndex)
tree:traverse(optimizer.inlineIndex)
tree:traverse(optimizer.inlineIndex)
tree:traverse(optimizer.tolocal)

optimizer.checkUselessFunctions()

tree = optimizer.loadCode(beautifier(tree), false)
for i=1, 5 do
	tree:traverse(cleaner.constantFolding)
end
tree:traverse(cleaner.removeUselessDo)
tree = optimizer.loadCode(beautifier(tree), false)
cleaner.removeUselessGoto(tree)

local finalCode = beautifier(tree)
if debug then
	print(finalCode)
else
	finalCode = [=[--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

-- Generated by make-engine-opt.lua
-- It is an inlined and optimized version of engine.lua
]=] .. finalCode


	local f = io.open('plume-data/engine/engine-opt.lua', 'w')
		f:write(finalCode)
	f:close()
end

