--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

-- Create std.lua by reading std/* and add type checking

local template = [=[
--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]


-- Generated by build-tools/make-std.lua

return function(plume)
	plume.std = {}
    plume.stdUtils = {}

	%s
end
]=]

local function makeSignature(name, signature, options)
	if (name == "call" or name == "validate") and options.meta then
		return "`$"..options.meta.."("..signature..")`"
	else
		return  "`$"..name.."("..signature..")`"
	end
end

local function process(f)
	f = f:gsub('%-%-%[%[.-%]%]', '') -- remove license

	f = f:gsub('%"([^"]+)%",%s*function%s*%(([^)]+)%)\n(%s*)(.-)%-%-!signature ([^\n]*)', function(name, args, indent, left, signature)

		local options = {}
		if signature:match('!') then
			local rawoptions
			signature, rawoptions = signature:match('^([^!]-)%s*!%s*([^!]-)$')

			for k, v in rawoptions:gmatch('(%S+):(%S+)') do
				options[k] = v
			end
		end

		local postionalArgsName = {}
		local namedArgsName = {}
		local optnPositionalArgs = {}
		local optnPositionalArgsCount = 0
		local allArgsName = {}
		local argsType = {}
		local canBeSelf = "nil"
		local variadic
		for m in signature:gmatch('[^,]+') do
			local isNamed = false
			local value
			local t, n = m:match('(%S+)%s+(%S+)')
			if not n then
				t = ""
				n = m:match("%S+")
			end
			local isVariadic, isIgnored

			n = n:gsub('%]$', ''):gsub('%)$', '')

			if n:match('|self') then
				n = n:gsub('|self', '')
				canBeSelf = #postionalArgsName
			end

			if n:match('^%?') then
				n = n:gsub('^%?', '')
				isNamed = true
				value = false
			elseif n:match(':') then
				n, value = n:match('([^:]+):(.*)')
				if value == "" then
					value = 'nil'
				elseif value == "\\s" then
					value = '" "'
				elseif value == "$empty" then
					value = '""'
				elseif not tonumber(value) then
					value = '"' .. value .. '"'
				end
				isNamed = true
			end

			if n:match('^%.%.%.') then
				variadic = n
				n = n:gsub('^%.%.%.', '')
				isVariadic = true
			end

			if t:match('^%(') then
				isIgnored = true
			end
			if t:match('^%[') then
				optnPositionalArgs[n] = true
				optnPositionalArgsCount = optnPositionalArgsCount+1
			end
			
			t = t:gsub('^%[', ''):gsub('^%(', '')
			if not isVariadic then
				if isNamed then
					table.insert(namedArgsName, n)
					namedArgsName[n] = value
				else
					table.insert(postionalArgsName, n)
				end
			end
			if not isIgnored and #t>0 then
				table.insert(allArgsName, n)
				if t ~= "any" then
					argsType[n] = t
				end
			end
		end

		signature = signature:gsub('%(', ''):gsub('%)', '') -- remove ignored syntax
		signature = signature:gsub('\\', '\\\\')

		signature = makeSignature(name, signature, options)

		local minArgCount = #postionalArgsName-optnPositionalArgsCount
		local maxArgCount = #postionalArgsName

		if variadic then
			maxArgCount = "math.huge"
		end

		local checks = {}
			if name == "call" and options.meta then
				table.insert(checks, 'local __name      = "' .. options.meta .. '"\n')
			else
				table.insert(checks, 'local __name      = "' .. name .. '"\n')
			end
			table.insert(checks, 'local __signature = "' .. signature .. '"\n')
			table.insert(checks, 'local __s, __e, self')
			if #postionalArgsName > 0 then
				local posList = table.concat(postionalArgsName, ", ")
				table.insert(checks, string.format(', %s\n', posList))
				table.insert(checks,string.format(
					'__s, __e, %s = plume.stdUnpackPositional(args, %s, %s,  __name, __signature)\n',
					posList, minArgCount, maxArgCount
				))
			else
				table.insert(checks, string.format(
					' = plume.stdUnpackPositional(args, 0, %s, __name, __signature)\n', 
					maxArgCount
				))
			end

			if #namedArgsName > 0 then
				local nList = table.concat(namedArgsName, ", ")
				local nListCheck = {}
				for _, key in ipairs(namedArgsName) do
					table.insert(nListCheck, string.format('"%s"', key))
				end
				table.insert(checks, string.format('local %s\n', nList))
				table.insert(checks, string.format(
					'if __s then __s, __e, self, %s = plume.stdUnpackNamed(args, {"self", %s}, __name, __signature) end\n',
					nList, table.concat(nListCheck, ", ")
				))

				for _, key in ipairs(namedArgsName) do
					table.insert(checks, string.format("%s = %s or %s\n", key, key, namedArgsName[key]))
				end
			else
				table.insert(checks, 'if __s then __s, __e, self = plume.stdUnpackNamed(args, {"self"}, __name, __signature) end\n')
			end

			local count = 0
			for _, argName in ipairs(allArgsName) do
				local checkArgName = argName
				if not namedArgsName[argName] then
					count = count + 1
					checkArgName = count
				end

				local expected = argsType[argName]
				if expected then
					if expected:match('|') then
						local first = true
						table.insert(checks, string.format("if __s and %s then\n\t", argName))
						for m in expected:gmatch('[^|]+') do
							if not first then
								table.insert(checks, "\tif not __s then\n\t\t")
							end
							table.insert(checks, string.format(
							'__s, __e, %s = plume.stdCheckType(%s, "%s", "%s", __name, __signature)\n',
								argName, argName, m, checkArgName
							))
							if first then
								first = false
							else
								table.insert(checks, "\tend\n")
							end
						end
						table.insert(checks, "end\n")
					else
						table.insert(checks, string.format(
						'if __s and %s then __s, __e, %s = plume.stdCheckType(%s, "%s", "%s", __name, __signature) end\n',
							argName, argName, argName, expected, checkArgName
						))
					end
				end
			end

			table.insert(checks, 'if not __s then return false, __e end\n')

		table.insert(checks, '------------')
		checks = (table.concat(checks):gsub('\n', '\n'..indent))

		return string.format('"%s", function (%s)\n%s%s%s', name, args, indent, left, checks)
	end)

	f = f:gsub('%-%-!override%-self%-(%S+)', 'if args.table.self and args.table.self ~= %1 then table.insert(args.table, 1, args.table.self) end')

	for m in f:gmatch('%-%-![^\n]+') do
		print(string.format("Warning: missed '%s'", m))
	end

	return f
end

local lfs = require "lfs"

local result = {}

for filename in lfs.dir("plume-data/engine/std") do
	if filename:match('%.lua$') then
		local file = io.open("plume-data/engine/std/"..filename)
		local content = file:read("*a")
		file:close()

		table.insert(result, process(content))
	end
end



result = string.format(template, (table.concat(result):gsub('\n', '\n\t')))
local out = io.open("plume-data/engine/std.lua", "w")
	out:write(result)
out:close()