local lfs = require "lfs"
local path = "plume-data/engine/vm"

local vmFiles = {}

for file in lfs.dir(path) do
	if not file:match('^%.+$') then
		table.insert(vmFiles, string.format("require '%s'", path .. "/" .. file:gsub('%.lua$', '')))
	end
end

local f = io.open('plume-data/engine/generated/vmloaders.lua', "w")
	f:write(string.format([=[--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

-- Generated by make-vmloaders.lua
return function (plume)
	plume.vmLoaders = {
		%s
	}
end
]=], table.concat(vmFiles, ",\n\t\t")))

f:close()