--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

local template = [=[
--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

-- Generated by build-tools/make-std-doc.lua

return function(plume)
%s
end
]=]


local f = io.open("doc/reference_std.md")
	local stddoc = f:read("*a")
f:close()

local function getDoc(name, suffix)
	local pattern1 = '%*%s*(`' ..(suffix or "")..'%.' .. name .. '[^\n]+)'
	local pattern2 = '%*%s*(`'  .. name .. '[^\n]+)'
	return stddoc:match(pattern1) or stddoc:match(pattern2)
end

local plume = require"plume-data/engine/init"

local infos = {}
for k, v in pairs(plume.std) do
	if v.type == "luaMacro" then
		local doc = getDoc(k)
		if doc then
			table.insert(infos, {k, doc})
		end
	elseif v.type == "table" then
		for kk, vv in pairs(v.table) do
			if type(vv) == "table" and vv.type == "luaMacro" then
				local doc = getDoc(kk, k)
				if doc then
					table.insert(infos, {k..".table."..kk, doc})
				end
			end
		end
	end
end

table.sort(infos, function(x, y) return x[1]<y[1] end)

local docs = {}

for _, info in ipairs(infos) do
	table.insert(docs, "\tplume.std." .. info[1] .. ".doc = [[" .. info[2] .. "]]")
end

f = io.open("plume-data/generated/stddoc.lua", "w")
	f:write(string.format(template, table.concat(docs, "\n")))
f:close()