--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

-- Optimize engine.lua to performances
-- Thanks for thenumbernine lua-parser lib.

package.path =  "build-tools/?.lua;build-tools/thenumbernine/?.lua;build-tools/thenumbernine/ext/?.lua;;build-tools/thenumbernine/parser/?.lua;;build-tools/thenumbernine/template/?.lua;" .. package.path

local ast = require "parser.lua.ast"
local tolua = require 'ext.tolua'
local optimizer = require"luaOptimizer"
local cleaner = require"luaCleaner"
local beautifier = require "luaBeautifier"

local function printTable(t)
	print(tolua(t))
end

local debug = false

require "make-engine" -- Compile base file
local tree

if debug then
	tree = optimizer.loadCode([[
if a then
	local x
	x = 5
else
	local x
	x = 5
	local y = 7
end
]], false)
else
	tree = optimizer.loadCode('plume-data/engine/generated/engine.lua', true)
end

-- printTable(tree)
tree = optimizer.optimize(tree)
tree = cleaner.clean(tree)

local finalCode = beautifier(tree)
if debug then
	print(finalCode)
else
	finalCode = [=[--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

-- Generated by make-engine-opt.lua
-- It is an inlined and optimized version of engine.lua
]=] .. finalCode

	finalCode = finalCode:gsub('function _ERROR', 'local function _ERROR') -- dirty fix waiting for #1072

	local f = io.open('plume-data/engine/generated/engine-opt.lua', 'w')
		f:write(finalCode)
	f:close()
end

