--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

-- Create the core big-dispatch-loop
-- Called by make-engine-opt.lua

require"build-tools/make-vmdoc"

plume = require"plume-data/engine/init"
local lfs = require "lfs"

local header = [=[--[[
This file is part of Plume🪶

Copyright © Erwan Barbedor
Licensed under the MIT License — see LICENSE for details.
]]

-- Generated by build-tools/make-engine.lua

-- This implementation is not (at all) aimed at optimization.
-- It allows the VM code (plume-data/engine/vm/*) to be made executable, while remaining readable and maintaining line consistency in error messages.
-- engine-opt is an automatically inlined and optimized version of this program.

-- Add all needed functions are loaded as globals
return function (plume)
	function plume._run_dev (vm, startip, fileID, variadicParam, namedParamOffset, initFileParams)
		--! index-to-inline self.err vmerr
	    --! index-to-inline self.errip vmerrip
	    --! index-to-inline vm.err vmerr
	    --! index-to-inline vm.errip vmerrip
	    --! index-to-inline self.* *
	    --! index-to-inline vm.* *
	    --! index-to-inline mainStack.*
	    --! index-to-inline variableStack.*
	    --! index-to-inline mainStackFrames.*
	    --! index-to-inline variableStackFrames.*
	    --! index-to-inline recursiveStack.*
	    --! index-to-inline fileStack.*
	    --! index-to-inline macroStack.*
	    --! index-to-inline contextStackCache.*
	    --! index-to-inline closureStack.*
	    --! index-to-inline flag.* *
	    --! index-to-inline runtime.*
	    --! index-to-inline plume.obj
	    --! index-to-inline plumeObj.*
	    --! index-to-inline plume._run_dev run
	    --! index-to-inline sops.* sops_*
	    
		local op, arg1, arg2, vmerr, vmerrip, customerrip
		local self = vm
		--! copyvm
		--! to-add local
		rshift = bit.rshift
		--! to-add local
		band = bit.band
		--! to-remove-begin
		vm._RUN    = plume._run_dev
		--! to-remove-end
		--! to-add vmstate._RUN = plume._run
		--! to-add local _RUN = vmstate._run
		vm.ip      = startip - 1
		vm:_VM_INIT(fileID)
		vm:_INIT_FILE_PARAM(fileID, initFileParams, variadicParam, namedParamOffset)
		
		
		::DISPATCH::
			do -- prevent
				op, arg1, arg2 = vm:_VM_DECODE_CURRENT_INSTRUCTION()
			end
]=]

local uselabelGoto = false

local dispatch, labels = {}, {}
local totalCount = 0
local op_namesTable = {}
for op_name in plume.ops_names:gmatch("%S+") do
	table.insert(op_namesTable, op_name)

	if op_name ~= "END" then
		table.insert(labels,string.format( "\t\t\t::%s::\n\t\t\t\t%s(vm, arg1, arg2)\n\t\t\t\tgoto DISPATCH\n", op_name, op_name))
	end
end

local function handleChoice(limDown, limUp, indent)
	indent = indent or "\t\t\t"
	local middlePoint = math.floor((limDown + limUp) / 2)
	
	table.insert(dispatch, string.format(indent.."if op < %i then\n", middlePoint))
	if middlePoint > 1 then
		if limUp - limDown > 2 then
			handleChoice(limDown, middlePoint, indent.."\t")
		else
			if  uselabelGoto or op_namesTable[middlePoint-1] == "END" then
				table.insert(dispatch, string.format(indent.."\tgoto %s\n", op_namesTable[middlePoint-1]))
			else
				table.insert(dispatch,string.format("\t\t\t\t\t\t\t\t\t\tvm:%s(arg1, arg2)\n", op_namesTable[middlePoint-1]))
			end
		end
	end
	
	if middlePoint <= #op_namesTable then
		table.insert(dispatch, indent.."else\n")
		if limUp - limDown > 2 then
			handleChoice(middlePoint+1, limUp, indent.."\t")
		else
			if uselabelGoto or op_namesTable[middlePoint] == "END" then
				table.insert(dispatch, string.format(indent.."\tgoto %s\n", op_namesTable[middlePoint]))
			else
				table.insert(dispatch,string.format("\t\t\t\t\t\t\t\t\t\tvm:%s(arg1, arg2)\n", op_namesTable[middlePoint]))
			end
		end
	end
	table.insert(dispatch, indent.."end\n")
end

local function makeDispatchBinary()
	-- Set to the nearest  2^n
	local totalCount = 2^(math.floor(1.5+math.log(#op_namesTable, 2)))
	handleChoice(0, totalCount)
end

local function makeDispatchFlat()
	for i, op_name in ipairs(op_namesTable) do
		table.insert(dispatch, "\t\t\t")
		if i>1 then
			table.insert(dispatch, "else")
		end
		table.insert(dispatch, string.format("if op == %i then", i))
		if uselabelGoto or op_name == "END" then
			table.insert(dispatch, string.format("\n\t\t\t\tgoto %s\n",op_name))
		else
			table.insert(dispatch,string.format("\n\t\t\t\t%s(vm, arg1, arg2)\n", op_name))
		end
	end
	table.insert(dispatch, "end\n")
end

makeDispatchBinary()
-- makeDispatchFlat()

dispatch = table.concat(dispatch)

if uselabelGoto then
	labels = table.concat(labels)
else
	labels = "goto DISPATCH"
end

local footer = [[
		--! to-add ::ERROR::
		--! to-add vm:_HANDLE_ERROR(customerrip)
		::END::
		
		--! to-remove-begin
		if not vm.err and vm:_STACK_POS(vm.recursiveStack) == 0 then
			local finalSuccess, finalMsg = vm:_FINAL_CHECKS ()
			if not finalSuccess then
				return false, finalMsg, #vm.runtime.bytecode
			end
		end
		if plume.runStatFlag then
			if plume.stats then
				for k, v in pairs(vm.stats.opseq) do
					plume.stats.opseq[k] = v + (plume.stats.opseq[k] or 0)
				end
			else
				plume.stats = {opseq=vm.stats.opseq}
			end
		end		
		--! to-remove-end

		vm:_RUN_END(vm)
		if vm.err then 
			return false, vm.err, vm.errip
		end

		return true, vm:_STACK_GET(vm.mainStack)
	end
end]]


local result = {header, dispatch, labels, footer}


local f = io.open("plume-data/generated/engine.lua", "w")
	f:write(table.concat( result, ""))
f:close()